from __future__ import annotations

from .artifacts import (
    CompilationModel,
    ExpandedCompilation,
    RustArtifacts,
    build_rust_artifacts,
    compile_artifact_files,
    compile_artifacts,
    parse_artifact_model,
    parse_compilation_model,
)
from .compiler import (
    AliasDecl,
    ArchitectureDecl,
    ArchitecturePort,
    BinaryExpr,
    BoolExpr,
    CallExpr,
    ExternDecl,
    FieldExpr,
    FunctionDecl,
    GlyphError,
    HostBindingDecl,
    HostBindingField,
    LambdaExpr,
    LetExpr,
    NameExpr,
    NumberExpr,
    OpaqueDecl,
    Param,
    ProductDecl,
    Program,
    StringExpr,
    SumDecl,
    SumVariant,
    TryExpr,
    TypeRef,
    UnaryExpr,
    compile_file,
    compile_source,
    parse_program,
)
from .compilation import (
    CompilationOutputs,
    CompilationPipeline,
    build_design_json,
    build_diagram_bundle,
    compile_text,
)
from .incremental import (
    CompilationSnapshot,
    IncrementalCompiler,
    IncrementalResult,
    watch_file,
)
from .preprocessor import PreprocessResult, preprocess_source as _preprocess_source
from .studio import GlyphStudio, StudioSnapshot


def preprocess_source(source: str) -> PreprocessResult:
    return _preprocess_source(source)


# Keep the package root as the stable user-facing facade. Glyph 0.4 IR models,
# semantic builders, validators, and code generators remain available from
# their responsibility-specific modules but are deliberately not re-exported.

__all__ = [
    "AliasDecl",
    "ArchitectureDecl",
    "ArchitecturePort",
    "BinaryExpr",
    "BoolExpr",
    "CallExpr",
    "CompilationModel",
    "CompilationOutputs",
    "CompilationPipeline",
    "CompilationSnapshot",
    "ExpandedCompilation",
    "ExternDecl",
    "FieldExpr",
    "FunctionDecl",
    "GlyphError",
    "GlyphStudio",
    "HostBindingDecl",
    "HostBindingField",
    "IncrementalCompiler",
    "IncrementalResult",
    "LambdaExpr",
    "LetExpr",
    "NameExpr",
    "NumberExpr",
    "OpaqueDecl",
    "Param",
    "PreprocessResult",
    "ProductDecl",
    "Program",
    "RustArtifacts",
    "StringExpr",
    "StudioSnapshot",
    "SumDecl",
    "SumVariant",
    "TryExpr",
    "TypeRef",
    "UnaryExpr",
    "build_design_json",
    "build_diagram_bundle",
    "build_rust_artifacts",
    "compile_artifact_files",
    "compile_artifacts",
    "compile_file",
    "compile_source",
    "compile_text",
    "parse_artifact_model",
    "parse_compilation_model",
    "parse_program",
    "preprocess_source",
    "watch_file",
]
