from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .compiler import (
    ExternDecl,
    FunctionDecl,
    GlyphError,
    Program,
    RustGenerator,
    parse_program,
)


@dataclass(frozen=True)
class RustArtifacts:
    logic: str
    host: str


def _inline_effect_lines(source: str) -> set[int]:
    """Return 1-based line numbers for `!signature=expr` declarations."""
    lines: set[int] = set()
    for line_no, original in enumerate(source.splitlines(), start=1):
        clean = original.split("#", 1)[0].rstrip()
        if not clean or clean[0].isspace() or not clean.startswith("!"):
            continue
        if "=" in clean:
            lines.add(line_no)
    return lines


def _parse_effect_program(source: str) -> tuple[Program, tuple[FunctionDecl, ...]]:
    """Parse inline effects as temporary functions, then split them from logic."""
    inline_lines = _inline_effect_lines(source)
    transformed: list[str] = []
    for line_no, original in enumerate(source.splitlines(), start=1):
        if line_no in inline_lines:
            bang = original.index("!")
            original = original[:bang] + ">" + original[bang + 1 :]
        transformed.append(original)

    parsed = parse_program("\n".join(transformed))
    effects: list[FunctionDecl] = []
    logic_declarations = []

    for decl in parsed.declarations:
        if isinstance(decl, FunctionDecl) and decl.line in inline_lines:
            effects.append(decl)
            logic_declarations.append(
                ExternDecl(decl.name, decl.params, decl.return_type, decl.line)
            )
        else:
            logic_declarations.append(decl)

    return Program(tuple(logic_declarations)), tuple(effects)


def _generate_host(program: Program, inline_effects: tuple[FunctionDecl, ...]) -> str:
    generator = RustGenerator(program)
    inline_by_name = {decl.name: decl for decl in inline_effects}
    externs = [decl for decl in program.declarations if isinstance(decl, ExternDecl)]

    out = [
        "// @generated by glyphc. Do not edit by hand.",
        "use crate::generated::*;",
        "",
    ]

    for decl in externs:
        signature = generator._signature_tail(decl.params, decl.return_type)
        out.append("#[allow(unused_variables)]")
        out.append(f"pub fn {decl.name}{signature} {{")
        implementation = inline_by_name.get(decl.name)
        if implementation is None:
            out.append(
                f'    panic!("Glyph effect boundary `{decl.name}` is not connected")'
            )
        elif implementation.expression is not None:
            out.append(f"    {generator._expr(implementation.expression)}")
        else:
            raise GlyphError(
                f"{implementation.line}行目: !境界の試作実装は単一式で記述する"
            )
        out.extend(["}", ""])

    return "\n".join(out).rstrip() + "\n"


def compile_artifacts(source: str) -> RustArtifacts:
    program, inline_effects = _parse_effect_program(source)
    logic = RustGenerator(program).generate()
    host = _generate_host(program, inline_effects)
    return RustArtifacts(logic=logic, host=host)


def compile_artifact_files(
    input_path: str | Path,
    logic_output_path: str | Path,
    host_output_path: str | Path,
) -> None:
    source = Path(input_path).read_text(encoding="utf-8")
    artifacts = compile_artifacts(source)

    logic_output = Path(logic_output_path)
    logic_output.parent.mkdir(parents=True, exist_ok=True)
    logic_output.write_text(artifacts.logic, encoding="utf-8")

    host_output = Path(host_output_path)
    host_output.parent.mkdir(parents=True, exist_ok=True)
    host_output.write_text(artifacts.host, encoding="utf-8")
