from __future__ import annotations

_MARKER = "glyph-diagram-editor-exports-v1"

_STYLE = r"""
<style id="glyph-diagram-editor-exports-v1-style">
:root{color-scheme:light;--bg:#f4f6f8;--panel:#fff;--panel2:#f8fafc;--panel3:#eef2f6;--line:#d7dde5;--text:#18212f;--muted:#667085;--faint:#98a2b3;--blue:#2563eb;--green:#16865b;--purple:#7557b7;--red:#c73546;--amber:#9a6700;--shadow:0 12px 32px rgba(16,24,40,.10)}
body{background:var(--bg)!important;color:var(--text)!important}header,.toolbar,.viewer-head,.diagnostics,.editor-pane,.lines{background:#fff!important}.editor{background:#fbfcfe!important;color:#1f2937!important}
.canvas-shell{background:linear-gradient(rgba(15,23,42,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(15,23,42,.035) 1px,transparent 1px),#fff!important;background-size:24px 24px!important;box-shadow:var(--shadow)!important}
.graph-node,.state-node{background:#fff!important;border-color:#60758a!important;box-shadow:0 7px 18px rgba(16,24,40,.10)!important}.graph-node.effect{background:#fcfaff!important}.edge-label,.transition-label{background:#fff!important;color:#344054!important;border-color:#cfd7e2!important;box-shadow:0 2px 8px rgba(16,24,40,.08)}.transition-label.failure-transition{background:#fff7f8!important;color:#a42838!important}.initial-transition-path{stroke:#111827!important}.initial-dot{background:#111827!important}
.diagram-tools{display:flex;align-items:center;gap:6px;margin-left:8px;flex-wrap:wrap}.diagram-tools select,.diagram-tools button{height:34px;padding:6px 9px;background:#fff;color:#344054;border-color:#d0d5dd}.diagram-tools button:hover{background:#f2f4f7}.diagram-tools .export{font-weight:650}.diagram-tools .separator{width:1px;height:22px;background:#d0d5dd;margin:0 2px}
.graph-stage.editable .state-node,.graph-stage.editable .graph-node{cursor:grab;user-select:none;touch-action:none}.graph-stage.editable .dragging{cursor:grabbing;z-index:20;outline:2px solid rgba(37,99,235,.35);box-shadow:0 12px 28px rgba(37,99,235,.20)!important}.selected-node{outline:2px solid #2563eb!important;outline-offset:3px}
.theme-monochrome{--blue:#111;--green:#111;--purple:#111;--red:#111;--amber:#111;--text:#111;--muted:#333;--faint:#666;--line:#aaa}.theme-monochrome body,.theme-monochrome header,.theme-monochrome .toolbar,.theme-monochrome .viewer-head,.theme-monochrome .editor-pane,.theme-monochrome .lines,.theme-monochrome .canvas-shell{background:#fff!important;color:#111!important}.theme-monochrome .canvas-shell{background:#fff!important;box-shadow:none!important;border:1px solid #111!important}.theme-monochrome .state-node,.theme-monochrome .graph-node,.theme-monochrome .edge-label,.theme-monochrome .transition-label{background:#fff!important;border-color:#111!important;color:#111!important;box-shadow:none!important}.theme-monochrome .state-node.unreachable{opacity:1!important}.theme-monochrome .state-transition-path,.theme-monochrome .initial-transition-path,.theme-monochrome .edge-svg path{stroke:#111!important}.theme-monochrome .failure-transition{stroke-dasharray:7 5!important}
@media print{header,.editor-pane,.splitter,.viewer-head,.view-controls,.machine-meta,.analysis-panel,.legend,.type-section{display:none!important}body,.app,main,.viewer,.view-body{height:auto!important;overflow:visible!important;background:#fff!important}main{display:block!important}.view-body{padding:0!important}.canvas-shell{border:0!important;box-shadow:none!important;overflow:visible!important}}
</style>
"""

_SCRIPT = r"""
<script id="glyph-diagram-editor-exports-v1-script">
(()=>{
const root=document.documentElement,$=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)],num=v=>parseFloat(v||"0")||0,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));let selected=null,drag=null,cache=null;
const download=(blob,name)=>{const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)};
async function state(){if(cache)return cache;const r=await fetch("/api/state",{cache:"no-store"});if(!r.ok)throw Error("diagram state unavailable");return cache=await r.json()}
function nameOf(n){return n.querySelector(".state-name,.node-name")?.textContent?.trim()||"node"}
function key(stage){const tab=$(".tab.active")?.dataset.tab||"state",i=tab==="state"?$("#machine-select")?.value||0:$("#system-select")?.value||0;return `glyph.diagram.positions.v1:${cache?.digest||"source"}:${tab}:${i}`}
function save(stage){const value={};stage.querySelectorAll(".state-node,.graph-node").forEach(n=>value[nameOf(n)]={x:num(n.style.left),y:num(n.style.top)});localStorage.setItem(key(stage),JSON.stringify(value))}
function restore(stage){let value;try{value=JSON.parse(localStorage.getItem(key(stage))||"null")}catch{}if(!value)return false;let changed=false;stage.querySelectorAll(".state-node,.graph-node").forEach(n=>{const p=value[nameOf(n)];if(p){n.style.left=`${p.x}px`;n.style.top=`${p.y}px`;changed=true}});return changed}
function stateCurve(a,b,same,i){const x1=a.offsetLeft+a.offsetWidth/2,y1=a.offsetTop+a.offsetHeight/2,x2=b.offsetLeft+b.offsetWidth/2,y2=b.offsetTop+b.offsetHeight/2;if(same){const s=58+i%3*14;return `M ${x1-27} ${y1-34} C ${x1-s} ${y1-98}, ${x1+s} ${y1-98}, ${x1+27} ${y1-34}`}const dx=x2-x1,dy=y2-y1,l=Math.max(1,Math.hypot(dx,dy)),sx=x1+dx/l*a.offsetWidth/2,sy=y1+dy/l*a.offsetHeight/2,tx=x2-dx/l*b.offsetWidth/2,ty=y2-dy/l*b.offsetHeight/2,o=(i%3-1)*22;return `M ${sx} ${sy} Q ${(sx+tx)/2-dy*.1+o} ${(sy+ty)/2+dx*.1+o} ${tx} ${ty}`}
async function reroute(stage){const data=await state(),svg=stage.querySelector(":scope > svg.edge-svg");if(!svg)return;if(stage.querySelector(".state-node")){const rows=data.views?.state?.machines||[],mn=$("#machine-select")?.selectedOptions?.[0]?.textContent,m=rows.find(x=>x.name===mn)||rows[0],nodes=new Map([...stage.querySelectorAll(".state-node")].map(n=>[nameOf(n),n])),paths=[...svg.querySelectorAll("path.state-transition-path")],labels=[...stage.querySelectorAll(".transition-label")];(m?.transitions||[]).forEach((t,i)=>{const a=nodes.get(t.source_state),b=nodes.get(t.target_state);if(!a||!b)return;paths[i]?.setAttribute("d",stateCurve(a,b,a===b,i));if(labels[i]){labels[i].style.left=`${(a.offsetLeft+b.offsetLeft+a.offsetWidth)/2+(i%3-1)*18}px`;labels[i].style.top=`${(a.offsetTop+b.offsetTop+a.offsetHeight)/2-(a===b?80:0)+(i%2)*12}px`}});delete stage.dataset.initialTransitionRouting;document.dispatchEvent(new CustomEvent("glyph-transition-input-action-labels-ready"))}else{const rows=data.views?.io?.systems||[],sn=$("#system-select")?.selectedOptions?.[0]?.textContent,s=rows.find(x=>x.name===sn)||rows[0],nodes=new Map([...stage.querySelectorAll(".graph-node")].map(n=>[nameOf(n),n])),paths=[...svg.querySelectorAll(":scope > path")],labels=[...stage.querySelectorAll(".edge-label")];(s?.edges||[]).forEach((e,i)=>{const source=(s.nodes||[]).find(n=>n.id===e.source_id)?.name,target=(s.nodes||[]).find(n=>n.id===e.target_id)?.name,a=nodes.get(source),b=nodes.get(target);if(!a||!b)return;const x1=a.offsetLeft+a.offsetWidth,y1=a.offsetTop+a.offsetHeight/2,x2=b.offsetLeft,y2=b.offsetTop+b.offsetHeight/2,m=Math.max(60,(x2-x1)*.48);paths[i]?.setAttribute("d",`M ${x1} ${y1} C ${x1+m} ${y1}, ${x2-m} ${y2}, ${x2} ${y2}`);if(labels[i]){labels[i].style.left=`${(a.offsetLeft+b.offsetLeft+a.offsetWidth)/2}px`;labels[i].style.top=`${(a.offsetTop+b.offsetTop+a.offsetHeight)/2}px`}})}}
function select(n){selected?.classList.remove("selected-node");selected=n;selected?.classList.add("selected-node")}
function ready(stage){return stage.querySelector(".state-node")?stage.dataset.umlTransitionReady==="true"&&stage.dataset.initialRouteReady==="true":true}
function edit(stage){if(stage.dataset.editorReady==="true"||!ready(stage))return;stage.dataset.editorReady="true";stage.classList.add("editable");const restored=restore(stage);if(restored)reroute(stage).catch(()=>{});stage.querySelectorAll(".state-node,.graph-node").forEach(n=>{n.onpointerdown=e=>{if(e.button)return;e.preventDefault();select(n);n.classList.add("dragging");n.setPointerCapture(e.pointerId);drag={n,stage,x:e.clientX,y:e.clientY,l:num(n.style.left),t:num(n.style.top)}};n.onpointermove=e=>{if(!drag||drag.n!==n)return;const g=e.shiftKey?1:8;n.style.left=`${Math.round(clamp(drag.l+e.clientX-drag.x,8,stage.scrollWidth-n.offsetWidth-8)/g)*g}px`;n.style.top=`${Math.round(clamp(drag.t+e.clientY-drag.y,8,stage.scrollHeight-n.offsetHeight-8)/g)*g}px`;reroute(stage).catch(()=>{})};n.onpointerup=()=>{if(!drag||drag.n!==n)return;n.classList.remove("dragging");save(stage);reroute(stage).catch(()=>{});drag=null};n.onclick=e=>{e.stopPropagation();select(n)}});stage.onclick=()=>select(null)}
const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c])),txt=(x,y,v,s=12,w=400,a="start")=>`<text x="${x}" y="${y}" font-family="Arial,Helvetica,sans-serif" font-size="${s}" font-weight="${w}" text-anchor="${a}" fill="#111">${esc(v)}</text>`;
function svg(){const stage=$(".graph-stage");if(!stage)throw Error("表示中の図がない");const W=Math.ceil(stage.scrollWidth),H=Math.ceil(stage.scrollHeight);let body="";const edge=stage.querySelector(":scope > svg.edge-svg");if(edge){const c=edge.cloneNode(true);c.querySelectorAll("path").forEach(p=>{p.setAttribute("stroke",root.classList.contains("theme-monochrome")?"#111":p.classList.contains("failure-transition")?"#c73546":"#60758a");p.setAttribute("fill","none")});body+=c.innerHTML}const dot=stage.querySelector(".initial-dot");if(dot)body+=`<circle cx="${dot.offsetLeft+9}" cy="${dot.offsetTop+9}" r="9" fill="#111"/>`;stage.querySelectorAll(".state-node").forEach(n=>{const x=n.offsetLeft,y=n.offsetTop,w=n.offsetWidth,h=n.offsetHeight,d=n.classList.contains("unreachable")?' stroke-dasharray="7 5"':'';body+=`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${h/2}" fill="#fff" stroke="#111" stroke-width="2"${d}/>${txt(x+w/2,y+h/2+4,nameOf(n),14,700,"middle")}`});stage.querySelectorAll(".graph-node").forEach(n=>{const x=n.offsetLeft,y=n.offsetTop,w=n.offsetWidth,h=n.offsetHeight;body+=`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="10" fill="#fff" stroke="#111"/>${txt(x+12,y+24,nameOf(n),15,700)}`;[...n.querySelectorAll(".port-text")].forEach((p,i)=>body+=txt(x+12,y+52+i*16,p.textContent,10))});stage.querySelectorAll(".edge-label").forEach(l=>{const x=l.offsetLeft-l.offsetWidth/2,y=l.offsetTop-l.offsetHeight/2,w=l.offsetWidth,h=l.offsetHeight;body+=`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="4" fill="#fff" stroke="#777"/>${txt(x+w/2,y+h/2+4,l.textContent,10,500,"middle")}`});return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="#fff"/>${body}</svg>`}
function base(){return ($("#machine-select")?.selectedOptions?.[0]?.textContent||$("#system-select")?.selectedOptions?.[0]?.textContent||"glyph-diagram").trim().replace(/[^A-Za-z0-9._-]+/g,"-")}
async function canvas(){const image=new Image(),u=URL.createObjectURL(new Blob([svg()],{type:"image/svg+xml"}));await new Promise((ok,no)=>{image.onload=ok;image.onerror=no;image.src=u});const c=document.createElement("canvas");c.width=image.naturalWidth*2;c.height=image.naturalHeight*2;const x=c.getContext("2d");x.scale(2,2);x.fillStyle="#fff";x.fillRect(0,0,image.naturalWidth,image.naturalHeight);x.drawImage(image,0,0);URL.revokeObjectURL(u);return c}
function bin(bytes){let s="";for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return s}
async function pdf(){const c=await canvas(),jpg=Uint8Array.from(atob(c.toDataURL("image/jpeg",.94).split(",")[1]),x=>x.charCodeAt(0)),PW=841.89,PH=595.28,r=Math.min(785/c.width,539/c.height),w=c.width*r,h=c.height*r,x=(PW-w)/2,y=(PH-h)/2,stream=`q\n${w} 0 0 ${h} ${x} ${y} cm\n/Im0 Do\nQ\n`,obj=["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>",`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PW} ${PH}] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>`,null,`<< /Length ${stream.length} >>\nstream\n${stream}endstream`];let p="%PDF-1.4\n%\xE2\xE3\xCF\xD3\n",off=[0];obj.forEach((o,i)=>{off.push(p.length);p+=`${i+1} 0 obj\n`;if(i===3)p+=`<< /Type /XObject /Subtype /Image /Width ${c.width} /Height ${c.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpg.length} >>\nstream\n${bin(jpg)}\nendstream`;else p+=o;p+="\nendobj\n"});const xr=p.length;p+=`xref\n0 6\n0000000000 65535 f \n`;off.slice(1).forEach(o=>p+=`${String(o).padStart(10,"0")} 00000 n \n`);p+=`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xr}\n%%EOF`;download(new Blob([Uint8Array.from(p,c=>c.charCodeAt(0)&255)],{type:"application/pdf"}),`${base()}.pdf`)}
function tools(){const h=$(".viewer-head");if(!h||$("#diagram-tools"))return;const d=document.createElement("div");d.id="diagram-tools";d.className="diagram-tools";d.innerHTML='<select id="diagram-theme"><option value="white">White</option><option value="monochrome">Monochrome</option></select><span class="separator"></span><button id="diagram-reset">Auto layout</button><button id="diagram-svg" class="export">SVG</button><button id="diagram-png" class="export">PNG</button><button id="diagram-pdf" class="export">PDF</button>';h.appendChild(d);const theme=localStorage.getItem("glyph.diagram.theme")||"white";$("#diagram-theme").value=theme;root.classList.toggle("theme-monochrome",theme==="monochrome");$("#diagram-theme").onchange=e=>{localStorage.setItem("glyph.diagram.theme",e.target.value);root.classList.toggle("theme-monochrome",e.target.value==="monochrome")};$("#diagram-reset").onclick=()=>{const s=$(".graph-stage");if(s)localStorage.removeItem(key(s));location.reload()};$("#diagram-svg").onclick=()=>download(new Blob([svg()],{type:"image/svg+xml"}),`${base()}.svg`);$("#diagram-png").onclick=async()=>{const c=await canvas();c.toBlob(b=>b&&download(b,`${base()}.png`),"image/png")};$("#diagram-pdf").onclick=()=>pdf().catch(e=>alert(e.message))}
document.addEventListener("keydown",e=>{if(!selected||!e.key.startsWith("Arrow"))return;e.preventDefault();const s=e.shiftKey?1:8,dx=e.key==="ArrowLeft"?-s:e.key==="ArrowRight"?s:0,dy=e.key==="ArrowUp"?-s:e.key==="ArrowDown"?s:0;selected.style.left=`${Math.max(0,num(selected.style.left)+dx)}px`;selected.style.top=`${Math.max(0,num(selected.style.top)+dy)}px`;const stage=selected.closest(".graph-stage");save(stage);reroute(stage).catch(()=>{})});
function enhance(){tools();const stage=$(".graph-stage");if(stage)edit(stage)}new MutationObserver(()=>setTimeout(enhance,20)).observe(document.body,{childList:true,subtree:true});document.addEventListener("glyph-uml-transition-ready",enhance);document.addEventListener("glyph-initial-transition-ready",enhance);enhance();
})();
</script>
"""


def enhance_diagram_editor_exports_html(html: str) -> str:
    """Add editable node positions, white themes, and SVG/PNG/PDF exports."""
    if _MARKER in html:
        return html
    return html.replace("</head>", _STYLE + "\n</head>").replace("</body>", _SCRIPT + "\n</body>")
