from __future__ import annotations

import re

from .host_requirements import HostOperationRequirement, HostRequirementModel


def _snake(text: str) -> str:
    output = re.sub(r"[^A-Za-z0-9]+", "_", text)
    output = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", output)
    output = output.strip("_").lower()
    if not output:
        return "requirement"
    if output[0].isdigit():
        output = "r_" + output
    return output


def _method_names(operations: tuple[HostOperationRequirement, ...]) -> dict[str, str]:
    used: dict[str, int] = {}
    output: dict[str, str] = {}
    for operation in operations:
        base = _snake(operation.kind + "_" + operation.subject)
        index = used.get(base, 0)
        used[base] = index + 1
        output[operation.id] = base if index == 0 else f"{base}_{index + 1}"
    return output


def _port_type(representation_types: dict[str, str], representation: str | None) -> str:
    if representation is None:
        return "Self::OpaqueValue"
    return f"Self::{representation_types[representation]}"


def render_host_binding_trait(model: HostRequirementModel) -> str:
    """Render a program-specific Host Binding contract without choosing a runtime."""

    representation_types = {item.id: item.associated_type for item in model.representations}
    method_names = _method_names(model.operations)
    out = [
        "// @generated by glyphc. Do not edit by hand.",
        "// This file contains representation-neutral semantic Host requirements.",
        "// Concrete ownership, scheduling, transport, timing, recovery, and device",
        "// mechanisms are selected only by the project-specific implementation.",
        "",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "pub struct HostRequirementContext {",
        "    pub id: &'static str,",
        "    pub kind: &'static str,",
        "    pub subject: &'static str,",
        "    pub contract: Option<&'static str>,",
        "}",
        "",
        "pub trait GlyphHostBinding {",
        "    type Error;",
        "    type OpaqueValue;",
    ]

    for slot in model.representations:
        out.append(f"    type {slot.associated_type};")

    if model.representations:
        out.append("")

    for operation in model.operations:
        for statement in operation.preconditions:
            out.append(f"    /// Pre: {statement}")
        for statement in operation.postconditions:
            out.append(f"    /// Post: {statement}")
        out.append(f"    /// Requirement: {operation.id}")
        parameters = ["&self", "context: HostRequirementContext"]
        for port in operation.inputs:
            parameters.append(
                f"{_snake(port.name)}: "
                + _port_type(representation_types, port.representation)
            )
        if not operation.outputs:
            result = "()"
        elif len(operation.outputs) == 1:
            result = _port_type(representation_types, operation.outputs[0].representation)
        else:
            result = "(" + ", ".join(
                _port_type(representation_types, item.representation)
                for item in operation.outputs
            ) + ")"
        out.append(
            f"    fn {method_names[operation.id]}("
            + ", ".join(parameters)
            + f") -> Result<{result}, Self::Error>;"
        )
        out.append("")

    if not model.operations:
        out.extend(
            [
                "    /// No runtime operation is required by this Glyph source.",
                "    fn no_requirements(&self) -> Result<(), Self::Error>;",
                "",
            ]
        )

    out.append("}")
    out.append("")
    return "\n".join(out)
