from __future__ import annotations

import hashlib
import re

from .host_requirements import HostOperationRequirement, HostRequirementModel


def _snake(text: str) -> str:
    output = re.sub(r"[^A-Za-z0-9]+", "_", text)
    output = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", output)
    output = output.strip("_").lower()
    if not output:
        return "requirement"
    if output[0].isdigit():
        output = "r_" + output
    return output


def _method_names(
    operations: tuple[HostOperationRequirement, ...],
) -> dict[str, str]:
    """Build names that remain stable when unrelated operations are inserted."""

    bases = {
        operation.id: _snake(operation.kind + "_" + operation.subject)
        for operation in operations
    }
    counts: dict[str, int] = {}
    for base in bases.values():
        counts[base] = counts.get(base, 0) + 1

    output: dict[str, str] = {}
    for operation in operations:
        base = bases[operation.id]
        if counts[base] == 1:
            output[operation.id] = base
            continue
        digest = hashlib.sha1(operation.id.encode("utf-8")).hexdigest()[:8]
        output[operation.id] = f"{base}_{digest}"
    return output


def _port_type(
    representation_types: dict[str, str],
    representation: str,
) -> str:
    try:
        associated_type = representation_types[representation]
    except KeyError as exc:
        raise ValueError(
            f"unknown Host representation slot: {representation}"
        ) from exc
    return f"Self::{associated_type}"


def render_host_binding_trait(model: HostRequirementModel) -> str:
    """Render a program-specific Host Binding contract without choosing a runtime."""

    representation_types = {
        item.id: item.associated_type for item in model.representations
    }
    method_names = _method_names(model.operations)
    out = [
        "// @generated by glyphc. Do not edit by hand.",
        "// This file contains representation-neutral semantic Host requirements.",
        "// Concrete ownership, scheduling, transport, timing, recovery, and device",
        "// mechanisms are selected only by the project-specific implementation.",
        "",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "pub struct HostRequirementContext {",
        "    id: &'static str,",
        "    kind: &'static str,",
        "    subject: &'static str,",
        "    contract: Option<&'static str>,",
        "}",
        "",
        "impl HostRequirementContext {",
        "    pub const fn new(",
        "        id: &'static str,",
        "        kind: &'static str,",
        "        subject: &'static str,",
        "        contract: Option<&'static str>,",
        "    ) -> Self {",
        "        Self { id, kind, subject, contract }",
        "    }",
        "",
        "    pub const fn id(&self) -> &'static str { self.id }",
        "    pub const fn kind(&self) -> &'static str { self.kind }",
        "    pub const fn subject(&self) -> &'static str { self.subject }",
        "    pub const fn contract(&self) -> Option<&'static str> { self.contract }",
        "}",
        "",
        "pub trait GlyphHostBinding {",
        "    type Error;",
    ]

    for slot in model.representations:
        out.append(f"    type {slot.associated_type};")

    if model.representations:
        out.append("")

    for operation in model.operations:
        for statement in operation.preconditions:
            out.append(f"    /// Pre: {statement}")
        for statement in operation.postconditions:
            out.append(f"    /// Post: {statement}")
        out.append(f"    /// Requirement: {operation.id}")
        parameters = ["&self", "context: HostRequirementContext"]
        for port in operation.inputs:
            parameters.append(
                f"{_snake(port.name)}: "
                + _port_type(representation_types, port.representation)
            )
        if not operation.outputs:
            result = "()"
        elif len(operation.outputs) == 1:
            result = _port_type(
                representation_types,
                operation.outputs[0].representation,
            )
        else:
            result = "(" + ", ".join(
                _port_type(representation_types, item.representation)
                for item in operation.outputs
            ) + ")"
        out.append(
            f"    fn {method_names[operation.id]}("
            + ", ".join(parameters)
            + f") -> Result<{result}, Self::Error>;"
        )
        out.append("")

    if not model.operations:
        out.extend(
            [
                "    /// No runtime operation is required by this Glyph source.",
                "    fn no_requirements(&self) -> Result<(), Self::Error>;",
                "",
            ]
        )

    out.append("}")
    out.append("")
    return "\n".join(out)
