from __future__ import annotations


STUDIO_HTML = r'''<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Glyph Studio</title>
<style>
:root{color-scheme:dark;--bg:#101218;--panel:#191d25;--line:#303744;--text:#edf1f7;--muted:#98a2b3;--ok:#62d7a5;--bad:#ff7d8e;--accent:#8aa9ff;--rust:#d69dff;--decision:#e6cb6b;--model:#d4a75f;--runtime:#b184e8;--trusted:#7ca8b8}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 ui-sans-serif,system-ui,sans-serif;height:100vh;overflow:hidden}
header{height:58px;display:flex;align-items:center;gap:14px;padding:0 18px;border-bottom:1px solid var(--line);background:#14171e}
.brand{font-weight:760;font-size:17px}.path{color:var(--muted);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1}
.status{padding:5px 9px;border-radius:999px;background:#252b36}.status.ready{color:var(--ok)}.status.error{color:var(--bad)}
button{border:1px solid var(--line);background:#252b36;color:var(--text);border-radius:7px;padding:7px 11px;cursor:pointer}button.primary{background:#3659a8;border-color:#5579d2}button:hover{filter:brightness(1.12)}
main{height:calc(100vh - 58px);display:grid;grid-template-columns:minmax(350px,46%) 1fr}.editor-pane{border-right:1px solid var(--line);display:flex;flex-direction:column;min-width:0}
.pane-title{height:42px;padding:11px 14px;color:var(--muted);border-bottom:1px solid var(--line)}
textarea{flex:1;width:100%;resize:none;border:0;outline:0;background:#0f1116;color:#e7ecf4;padding:16px;font:13px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace;tab-size:2}
.viewer{min-width:0;display:flex;flex-direction:column}.tabs{height:42px;display:flex;gap:2px;padding:5px 8px;border-bottom:1px solid var(--line);overflow-x:auto}.tab{background:transparent;border:0;color:var(--muted);white-space:nowrap}.tab.active{color:var(--text);background:#252b36}
.content{flex:1;overflow:auto;padding:18px}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:10px}.card{background:var(--panel);border:1px solid var(--line);border-radius:9px;padding:13px}.card[data-line],.row[data-line],h2[data-line],.stage[data-line],.algorithm-step[data-line]{cursor:pointer}.card[data-line]:hover,.row[data-line]:hover,.stage[data-line]:hover,.algorithm-step[data-line]:hover{border-color:var(--accent)}
.value{font-size:24px;font-weight:700}.label,.muted{color:var(--muted)}.mono{font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace}.empty{color:var(--muted);border:1px dashed var(--line);border-radius:9px;padding:16px}
pre{white-space:pre-wrap;word-break:break-word;background:#0f1116;border:1px solid var(--line);border-radius:8px;padding:14px;font:12px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace}.error{border:1px solid #743844;background:#26171b;color:#ffc2ca;padding:12px;border-radius:8px;margin-bottom:12px}
.edge,.row{display:grid;grid-template-columns:minmax(120px,1fr) 36px minmax(120px,1fr) 100px;gap:8px;padding:8px;border-bottom:1px solid var(--line);align-items:center}.component{border-left:3px solid var(--accent)}.component.effect{border-left-color:var(--bad)}.component.rust{border-left-color:var(--rust)}.component.external{border-left-color:var(--muted)}.component.data{border-left-color:var(--ok)}
.symbol{display:grid;grid-template-columns:50px 120px 1fr 1fr;gap:9px;padding:7px;border-bottom:1px solid var(--line)}h2{font-size:16px;margin:5px 0 12px}h3{font-size:14px;margin:18px 0 8px}
.chips{display:flex;flex-wrap:wrap;gap:5px;margin-top:8px}.chip{display:inline-flex;align-items:center;border:1px solid var(--line);background:#11141a;border-radius:999px;padding:2px 7px;font-size:11px;color:var(--muted)}.chip.accent{border-color:#536b9b;color:var(--accent)}.chip.ok{border-color:#3f7662;color:var(--ok)}.chip.bad{border-color:#824854;color:var(--bad)}
.section{margin-bottom:25px}.applications{margin-top:10px;padding-top:8px;border-top:1px solid var(--line)}.application{display:flex;gap:7px;align-items:center;margin-top:5px}.line{margin-left:auto;color:var(--muted)}
.algorithm{margin-bottom:24px}.algorithm-step{border:1px solid var(--line);background:var(--panel);border-radius:10px;margin:9px 0;padding:12px}.step-head{display:flex;align-items:baseline;gap:9px;margin-bottom:9px}.step-name{font-weight:750}.type{font:12px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--ok)}.branches{display:grid;gap:6px}.branch{display:grid;grid-template-columns:minmax(120px,1fr) 30px minmax(120px,1fr);gap:8px;padding:8px;background:#11141a;border-radius:7px}.pipeline{display:flex;align-items:stretch;gap:7px;overflow-x:auto;padding:4px 0}.stage{min-width:145px;background:#11141a;border:1px solid var(--line);border-radius:8px;padding:9px}.stage.lambda{border-color:#7461a8}.stage.rust{border-color:var(--rust)}.stage.effect{border-color:var(--bad)}.stage.function{border-color:var(--accent)}.stage .kind{text-transform:uppercase;font-size:10px;letter-spacing:.08em;color:var(--muted)}.pipe-arrow{display:flex;align-items:center;color:var(--muted);font-size:18px}.err{color:var(--bad);font-size:11px;margin-top:5px}.expression{font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;background:#11141a;padding:9px;border-radius:7px}.return-step{border-color:var(--ok)}
.identity{border-left:3px solid var(--ok)}.state-chain,.sequence{display:flex;align-items:stretch;gap:7px;overflow-x:auto;padding:8px 0}.state-node,.event-node,.graph-node{min-width:125px;border:1px solid var(--line);background:#11141a;border-radius:8px;padding:9px}.state-node{border-color:#3f7662}.event-node.send{border-color:#526ca5}.event-node.receive{border-color:#3f7662}.graph-node.handler{border-color:#765a9e}.graph-node.exit{border-color:#3f7662}.graph-node.target{border-color:#6c7480}.arrow{display:flex;align-items:center;color:var(--muted);font-size:18px}.direction{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}
.region{display:flex;align-items:center;flex-wrap:wrap;gap:5px;margin-top:8px}.region-part{border:1px solid var(--line);border-radius:6px;padding:4px 8px;background:#11141a}.region-separator{color:var(--muted)}
.strength-grid{display:grid;grid-template-columns:repeat(4,minmax(120px,1fr));gap:9px}.strength{border-top:3px solid var(--accent)}.strength.model{border-top-color:var(--model)}.strength.runtime{border-top-color:var(--runtime)}.strength.trusted{border-top-color:var(--trusted)}
table{width:100%;border-collapse:collapse;background:var(--panel);border:1px solid var(--line)}th,td{text-align:left;padding:8px;border-bottom:1px solid var(--line)}th{color:var(--muted);font-weight:500}.count{text-align:center}.formula{max-height:260px;overflow:auto}
@media(max-width:850px){main{grid-template-columns:1fr}.editor-pane{display:none}.strength-grid{grid-template-columns:repeat(2,minmax(120px,1fr))}.edge,.row{grid-template-columns:1fr 25px 1fr}.edge>:last-child,.row>:last-child{display:none}}
</style>
</head>
<body>
<header><div class="brand">Glyph Studio</div><div id="path" class="path"></div><div id="status" class="status">starting</div><button id="rebuild">Rebuild</button><button id="save" class="primary">Save</button></header>
<main><section class="editor-pane"><div class="pane-title">Source</div><textarea id="editor" spellcheck="false"></textarea></section><section class="viewer"><nav id="tabs" class="tabs"></nav><div id="content" class="content"></div></section></main>
<script>
const tabs=[
  'Overview','Capability','Resource','World/Region','Protocol','Handler','Law/Monitor','Verification',
  'Architecture','State','Logic','Flow','Time','Rust','Host','Manual','AST','Symbols','Artifacts'
];
let active='Overview',state=null,dirty=false,lastVersion=-1;
const editor=document.getElementById('editor'),content=document.getElementById('content');
editor.addEventListener('input',()=>dirty=true);
document.getElementById('save').addEventListener('click',async()=>{await post('/api/save',{source:editor.value});dirty=false;await refresh(true)});
document.getElementById('rebuild').addEventListener('click',async()=>{await post('/api/rebuild',{});await refresh(true)});
content.addEventListener('click',event=>{const target=event.target.closest('[data-line]');if(target)goLine(target.dataset.line)});
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function lineAttr(line){return Number(line)>0?` data-line="${Number(line)}"`:''}
function chips(values,kind=''){return (values||[]).map(value=>`<span class="chip ${kind}">${esc(value)}</span>`).join('')}
function applications(items){if(!(items||[]).length)return '';return `<div class="applications"><div class="muted">Applied to</div>${items.map(item=>`<div class="application"${lineAttr(item.line)}><span class="chip accent">${esc(item.target_kind||'target')}</span><b>${esc(item.target)}</b><span class="line">L${esc(item.line||'—')}</span></div>`).join('')}</div>`}
function empty(message){return `<div class="empty">${esc(message)}</div>`}
function studioView(name){return state?.glyph04_views?.views?.[name]||{}}
async function post(url,body){return fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
async function artifact(name){const response=await fetch('/api/artifact?name='+encodeURIComponent(name));const value=await response.json();return value.content||''}
function goLine(line){const n=Math.max(1,Number(line)||1),text=editor.value,parts=text.split('\n');let start=0;for(let i=1;i<n;i++)start+=parts[i-1].length+1;const end=start+(parts[n-1]||'').length;editor.focus();editor.setSelectionRange(start,end);const lh=parseFloat(getComputedStyle(editor).lineHeight)||20;editor.scrollTop=Math.max(0,(n-3)*lh)}
function makeTabs(){document.getElementById('tabs').innerHTML=tabs.map(tab=>`<button class="tab ${tab===active?'active':''}" data-tab="${esc(tab)}">${esc(tab)}</button>`).join('');document.querySelectorAll('.tab').forEach(button=>button.addEventListener('click',()=>{active=button.dataset.tab;makeTabs();render()}))}
function diagnostics(){return (state.diagnostics||[]).map(diagnostic=>`<div class="error">${esc(diagnostic.message)}</div>`).join('')}
function overview(){const ir=state.execution_ir||{},semantic=state.semantic||{},summary=state.glyph04_views?.summary||{};const glyph04=state.glyph04_views?.enabled?`<h3>Glyph 0.4 design</h3><div class="cards"><div class="card"><div class="value">${summary.resources||0}</div><div class="label">Resources</div></div><div class="card"><div class="value">${summary.resource_identities||0}</div><div class="label">Resource identities</div></div><div class="card"><div class="value">${summary.worlds||0}</div><div class="label">Worlds</div></div><div class="card"><div class="value">${summary.protocols||0}</div><div class="label">Protocols</div></div><div class="card"><div class="value">${summary.handlers||0}</div><div class="label">Handlers</div></div><div class="card"><div class="value">${summary.laws||0}</div><div class="label">Laws</div></div></div>`:'';return diagnostics()+`<div class="cards"><div class="card"><div class="value">${(semantic.functions||[]).length}</div><div class="label">Functions</div></div><div class="card"><div class="value">${(semantic.blocks||[]).length}</div><div class="label">Algorithm blocks</div></div><div class="card"><div class="value">${(semantic.rust_todos||[]).length}</div><div class="label">Rust TODOs</div></div><div class="card"><div class="value">${(ir.machines||[]).length}</div><div class="label">Machines</div></div><div class="card"><div class="value">${(ir.temporal||[]).length}</div><div class="label">Time constraints</div></div><div class="card"><div class="value">${(semantic.symbols||[]).length}</div><div class="label">Symbols</div></div></div>${glyph04}<h3>Build</h3><pre>Status: ${esc(state.status)}\nUpdated: ${esc(state.updated_at)}\nDigest: ${esc((state.digest||'').slice(0,16))}\nOutput: ${esc(state.output_dir)}</pre>`}
function capabilityView(){const view=studioView('capability'),resources=view.resources||[],functions=view.functions||[],aggregates=view.aggregates||[],operations=view.operations||[];if(!resources.length&&!functions.length&&!aggregates.length&&!operations.length)return empty('Glyph 0.4 capability declarations are not present.');const resourceCards=resources.map(resource=>`<div class="card identity"${lineAttr(resource.line)}><b>${esc(resource.name)}</b><div class="muted">resource · L${esc(resource.line||'—')}</div><div class="chips">${chips(resource.states,'ok')}</div></div>`).join('');const functionCards=functions.map(fn=>`<div class="card"${lineAttr(fn.line)}><b>${esc(fn.name)}</b><div class="muted">${esc(fn.marker)} function · L${esc(fn.line||'—')}</div><div class="mono" style="margin-top:8px">${(fn.params||[]).map(param=>`${esc(param.name)}: ${esc(param.type?.raw||param.type?.name||'?')}`).join('<br>')||'()'}<br>→ ${esc(fn.result?.raw||fn.result?.name||'?')}</div></div>`).join('');const aggregateCards=aggregates.map(item=>`<div class="card"${lineAttr(item.line)}><b>${esc(item.name)}</b><div class="muted">aggregate · L${esc(item.line||'—')}</div><div class="chips">${(item.members||[]).map(member=>`<span class="chip">${esc(member.raw||member.name||'?')}</span>`).join('')}</div></div>`).join('');const opRows=operations.map(op=>`<div class="row"${lineAttr(op.line)}><b>${esc(op.function)}</b><span>→</span><span>${esc(op.kind)}</span><span class="mono">${esc(op.source||'')} ${op.target?'→ '+esc(op.target):''}</span></div>`).join('');return `<section class="section"><h2>Capabilities and resource types</h2><div class="cards">${resourceCards}</div></section><section class="section"><h2>Capability-bearing functions</h2><div class="cards">${functionCards||empty('No capability-bearing functions.')}</div></section><section class="section"><h2>Stored capability shapes</h2><div class="cards">${aggregateCards||empty('No capability-bearing aggregate types.')}</div></section><section><h2>Capability operations</h2>${opRows||empty('No move, borrow, or conversion operations.')}</section>`}
function resourceView(){const identities=studioView('resource').identities||[];if(!identities.length)return empty('No symbolic resource identities were derived.');return identities.map(identity=>{const states=(identity.states||[]).map((stateName,index)=>`${index?'<span class="arrow">→</span>':''}<div class="state-node"><div class="direction">state ${index+1}</div><b>${esc(stateName)}</b></div>`).join('');const transitions=(identity.transitions||[]).map(transition=>`<div class="row"${lineAttr(transition.line)}><b>${esc(transition.function)}</b><span>→</span><span>${esc(transition.source?.state||'fresh')} → ${esc(transition.target?.state||'?')}</span><span class="chip">${esc(transition.kind)}</span></div>`).join('');return `<section class="section card identity"${lineAttr(identity.line)}><div class="step-head"><div><b>${esc(identity.resource)}</b><div class="mono muted">${esc(identity.identity)}</div></div><span class="line">L${esc(identity.line||'—')}</span></div><div class="chips">${chips(identity.capabilities,'accent')}</div><div class="state-chain">${states}</div><div>${transitions}</div></section>`}).join('')}
function worldRegionView(){const worlds=studioView('world_region').worlds||[];if(!worlds.length)return empty('No World or Region contracts are present.');return `<div class="cards">${worlds.map(world=>{const region=(world.region||[]).map((part,index)=>`${index?'<span class="region-separator">/</span>':''}<span class="region-part">${esc(part)}</span>`).join('');return `<div class="card"${lineAttr(world.line)}><div class="step-head"><b>${esc(world.name)}</b><span class="chip accent">${esc(world.locus)}</span><span class="line">L${esc(world.line||'—')}</span></div><div class="muted">Dynamic Region</div><div class="region">${region||'<span class="muted">root</span>'}</div>${applications(world.applications)}</div>`}).join('')}</div>`}
function protocolView(){const protocols=studioView('protocol').protocols||[];if(!protocols.length)return empty('No Protocol contracts are present.');return protocols.map(protocol=>{const events=(protocol.events||[]).map((event,index)=>`${index?'<span class="arrow">→</span>':''}<div class="event-node ${esc(event.direction)}"><div class="direction">${event.direction==='send'?'send →':'receive ←'}</div><b>${esc(event.type||'?')}</b><div class="mono muted">${esc(event.path)}</div><div class="chips">${chips(event.controls)}</div></div>`).join('');return `<section class="section card"${lineAttr(protocol.line)}><div class="step-head"><b>${esc(protocol.name)}</b><span class="line">L${esc(protocol.line||'—')}</span></div><div class="sequence">${events||'<span class="muted">No events.</span>'}</div>${applications(protocol.applications)}</section>`}).join('')}
function handlerView(){const handlers=studioView('handler').handlers||[];if(!handlers.length)return empty('No Handler contracts are present.');return handlers.map(handler=>{const byId=Object.fromEntries((handler.nodes||[]).map(node=>[node.id,node]));const chain=(handler.edges||[]).map((edge,index)=>{const source=byId[edge.source]||{},target=byId[edge.target]||{};return `${index===0?`<div class="graph-node ${esc(source.kind)}"${lineAttr(source.line)}><div class="direction">${esc(source.kind)}</div><b>${esc(source.label)}</b></div>`:''}<span class="arrow" title="${esc(edge.label)}">→</span><div class="graph-node ${esc(target.kind)}"${lineAttr(target.line)}><div class="direction">${esc(target.kind)}</div><b>${esc(target.label)}</b>${(target.arguments||[]).length?`<div class="mono muted">${esc(target.arguments.join(', '))}</div>`:''}<div class="chips">${chips(String(target.verification||'').split('+').filter(Boolean))}</div></div>`}).join('');return `<section class="section card"${lineAttr(handler.line)}><div class="step-head"><b>${esc(handler.name)}</b><span class="line">L${esc(handler.line||'—')}</span></div><div class="sequence">${chain}</div>${applications(handler.applications)}</section>`}).join('')}
function lawView(){const laws=studioView('law').laws||[];if(!laws.length)return empty('No Law contracts or monitor obligations are present.');return laws.map(law=>`<section class="section card"${lineAttr(law.line)}><div class="step-head"><b>${esc(law.name)}</b><div class="chips">${chips(String(law.verification||'').split('+').filter(Boolean),'accent')}</div><span class="line">L${esc(law.line||'—')}</span></div><pre class="formula">${esc(JSON.stringify(law.formula||{},null,2))}</pre>${(law.requirements||[]).map(requirement=>`<div class="muted">Monitor requirement: ${esc(requirement.id||requirement.kind)}</div>`).join('')}${applications(law.applications)}</section>`).join('')}
function verificationView(){const view=studioView('verification_strength'),classes=view.classes||[],matrix=view.matrix||[],items=view.items||[];if(!items.length)return empty('No Glyph 0.4 verification report is present.');const cards=classes.map(item=>`<div class="card strength ${esc(item.name)}"><div class="value">${item.count||0}</div><div class="label">${esc(item.name)}</div></div>`).join('');const head=['Axis','static','model','runtime','trusted'];const rows=matrix.map(row=>`<tr><td><b>${esc(row.axis)}</b></td>${head.slice(1).map(name=>`<td class="count">${row[name]||0}</td>`).join('')}</tr>`).join('');const itemRows=items.map(item=>`<div class="card"${lineAttr(item.line)} style="margin-bottom:8px"><div class="step-head"><b>${esc(item.subject)}</b><span class="chip">${esc(item.axis)}</span><span class="line">L${esc(item.line||'—')}</span></div><div>${esc(item.statement)}</div><div class="chips">${chips(item.classes||[],'accent')}</div></div>`).join('');return `<section class="section"><h2>Verification strength</h2><div class="strength-grid">${cards}</div></section><section class="section"><h2>Axis × guarantee class</h2><table><thead><tr>${head.map(name=>`<th>${esc(name)}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></section><section><h2>Obligations</h2>${itemRows}</section>`}
async function architecture(){let data={systems:[]};try{data=JSON.parse(await artifact('architecture-ir.json'))}catch(_){ }const systems=data.systems||[];if(!systems.length)return empty('system declaration is not present.');return systems.map(system=>{const byId=Object.fromEntries((system.components||[]).map(component=>[component.id,component]));const components=(system.components||[]).map(component=>`<div class="card component ${esc(component.kind)}"${lineAttr(component.line)}><b>${esc(component.name)}</b><div class="muted">${esc(component.kind)}${component.binding?' · '+esc(component.binding):''} · L${component.line}</div></div>`).join('');const edges=(system.edges||[]).map(edge=>`<div class="edge"${lineAttr(edge.line)}><b>${esc(byId[edge.source_id]?.name||edge.source_id)}</b><span>→</span><b>${esc(byId[edge.target_id]?.name||edge.target_id)}</b><span class="muted">L${edge.line}</span></div>`).join('');return `<h2>${esc(system.name)}</h2><div class="cards">${components}</div><h3>Connections</h3>${edges}`}).join('')}
function stateView(){const machines=state.execution_ir?.machines||[];if(!machines.length)return empty('machine declaration is not present.');return machines.map(machine=>{const transitions=(machine.transitions||[]).map(transition=>`<div class="edge"${lineAttr(transition.source?.line||machine.source?.line||1)}><b>${esc(transition.source_state)}</b><span>→</span><b>${esc(transition.target_state)}</b><span>${esc(transition.condition)}</span></div>`).join('');return `<h2>${esc(machine.name)}</h2><pre>initial: ${esc(machine.initial_state)}\nsuccess: ${esc(machine.success_state)}\nfailure: ${esc(machine.failure_state)}</pre><h3>Transitions</h3>${transitions}`}).join('')}
function renderPipeline(value){const first=`<div class="stage value"><div class="kind">INPUT</div><b>${esc(value.input_text||'value')}</b><div class="muted">${esc(value.input_type||'')}</div></div>`;const stages=(value.stages||[]).map(stage=>`<div class="pipe-arrow">→</div><div class="stage ${esc(stage.kind)}"${lineAttr(stage.source?.line||1)}><div class="kind">${esc(stage.kind)}</div><b>${esc(stage.label)}</b><div class="muted">${esc(stage.input_type||'?')} → ${esc(stage.output_type||'?')} · L${stage.source?.line||0}</div>${stage.propagates?'<div class="err">Err exits this function</div>':''}</div>`).join('');return `<div class="pipeline">${first}${stages}</div>`}
function renderValue(value){if(value.kind==='conditional')return `<div class="branches">${(value.branches||[]).map(branch=>`<div class="branch"${lineAttr(branch.source?.line||1)}><b>${esc(branch.condition==='_'?'otherwise':branch.condition)}</b><span>→</span><span>${esc(branch.value)}${(branch.binders||[]).length?`<div class="muted">bind ${esc(branch.binders.join(', '))}</div>`:''}</span></div>`).join('')}</div>`;if(value.kind==='pipeline')return renderPipeline(value);return `<div class="expression">${esc(value.source_text)}</div>`}
async function logic(){let data={functions:[]};try{data=JSON.parse(await artifact('algorithm-ir.json'))}catch(_){ }const functions=data.functions||[];if(!functions.length)return empty('No := algorithm blocks. Lowered compiler helpers are intentionally hidden.');return functions.map(fn=>`<section class="algorithm"><h2${lineAttr(fn.source?.line||1)}>${esc(fn.name)} <span class="type">→ ${esc(fn.return_type)}</span></h2>${(fn.steps||[]).map(step=>`<div class="algorithm-step ${step.kind==='return'?'return-step':''}"${lineAttr(step.source?.line||1)}><div class="step-head"><span class="step-name">${step.kind==='return'?'return':esc(step.name)}</span><span class="type">${esc(step.type)}</span><span class="line">L${step.source?.line||0}</span></div>${renderValue(step.value||{})}</div>`).join('')}</section>`).join('')}
function flowView(){const ir=state.execution_ir||{},nodes=ir.nodes||[],edges=ir.edges||[];const nodeCards=nodes.map(node=>`<div class="card component ${esc(node.kind)}"${lineAttr(node.source?.line||1)}><b>${esc(node.label)}</b><div class="muted">${esc(node.kind)} · L${node.source?.line||0}</div></div>`).join('');const edgeRows=edges.map(edge=>`<div class="edge"${lineAttr(edge.source?.line||1)}><b>${esc(edge.source_id)}</b><span>→</span><b>${esc(edge.target_id)}</b><span>${esc(edge.label||edge.kind)}</span></div>`).join('');return `<h2>Lowered execution flow</h2><div class="cards">${nodeCards}</div><h3>Edges</h3>${edgeRows||empty('No execution edges.')}`}
function timeView(){const items=state.execution_ir?.temporal||[];return `<h2>Time and safety constraints</h2>${items.map(item=>`<div class="card" style="margin-bottom:9px"${lineAttr(item.source?.line||1)}><b>${esc(item.name)}</b><pre>${esc(item.formula)}</pre><div class="muted">${esc(item.streaming_monitor)}</div></div>`).join('')||empty('No temporal constraints.')}`}
async function code(name){content.innerHTML='<div class="muted">loading…</div>';content.innerHTML='<pre>'+esc(await artifact(name))+'</pre>'}
function ast(){return '<pre>'+esc(JSON.stringify(state.semantic||{},null,2))+'</pre>'}
function symbols(){return `<div class="symbol muted"><span>ID</span><span>Kind</span><span>Name</span><span>Type</span></div>${(state.semantic?.symbols||[]).filter(symbol=>!String(symbol.name||'').startsWith('__glyph_')).map(symbol=>`<div class="symbol"><span>${symbol.id}</span><span>${esc(symbol.kind)}</span><b>${esc(symbol.name)}</b><span>${esc(symbol.type||'')}</span></div>`).join('')}`}
function artifacts(){return `<h2>Generated automatically</h2>${(state.artifact_names||[]).map(name=>`<div class="card" style="margin-bottom:8px"><b>${esc(name)}</b><div class="muted">${esc(state.output_dir+'/'+name)}</div></div>`).join('')}`}
async function render(){if(!state)return;document.getElementById('path').textContent=state.source_path;const status=document.getElementById('status');status.textContent=state.status;status.className='status '+state.status;if(active==='Overview')content.innerHTML=overview();else if(active==='Capability')content.innerHTML=capabilityView();else if(active==='Resource')content.innerHTML=resourceView();else if(active==='World/Region')content.innerHTML=worldRegionView();else if(active==='Protocol')content.innerHTML=protocolView();else if(active==='Handler')content.innerHTML=handlerView();else if(active==='Law/Monitor')content.innerHTML=lawView();else if(active==='Verification')content.innerHTML=verificationView();else if(active==='Architecture')content.innerHTML=await architecture();else if(active==='State')content.innerHTML=stateView();else if(active==='Logic')content.innerHTML=await logic();else if(active==='Flow')content.innerHTML=flowView();else if(active==='Time')content.innerHTML=timeView();else if(active==='Rust')await code('generated.rs');else if(active==='Host')await code('host.generated.rs');else if(active==='Manual')await code('manual.rs');else if(active==='AST')content.innerHTML=ast();else if(active==='Symbols')content.innerHTML=symbols();else content.innerHTML=artifacts()}
async function refresh(force=false){const response=await fetch('/api/state',{cache:'no-store'});const next=await response.json();if(force||next.version!==lastVersion){state=next;lastVersion=next.version;if(!dirty)editor.value=state.source||'';await render()}}
makeTabs();refresh(true);setInterval(()=>refresh(false),600);
</script>
</body>
</html>'''
