from __future__ import annotations


STUDIO_HTML = r'''<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Glyph Studio</title>
<style>
:root{color-scheme:dark;--bg:#101218;--panel:#191d25;--line:#303744;--text:#edf1f7;--muted:#98a2b3;--ok:#62d7a5;--bad:#ff7d8e;--accent:#8aa9ff;--rust:#d69dff;--decision:#e6cb6b}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 ui-sans-serif,system-ui,sans-serif;height:100vh;overflow:hidden}
header{height:58px;display:flex;align-items:center;gap:14px;padding:0 18px;border-bottom:1px solid var(--line);background:#14171e}.brand{font-weight:760;font-size:17px}.path{color:var(--muted);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1}.status{padding:5px 9px;border-radius:999px;background:#252b36}.status.ready{color:var(--ok)}.status.error{color:var(--bad)}
button{border:1px solid var(--line);background:#252b36;color:var(--text);border-radius:7px;padding:7px 11px;cursor:pointer}button.primary{background:#3659a8;border-color:#5579d2}button:hover{filter:brightness(1.12)}
main{height:calc(100vh - 58px);display:grid;grid-template-columns:minmax(350px,46%) 1fr}.editor-pane{border-right:1px solid var(--line);display:flex;flex-direction:column;min-width:0}.pane-title{height:42px;padding:11px 14px;color:var(--muted);border-bottom:1px solid var(--line)}textarea{flex:1;width:100%;resize:none;border:0;outline:0;background:#0f1116;color:#e7ecf4;padding:16px;font:13px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace;tab-size:2}
.viewer{min-width:0;display:flex;flex-direction:column}.tabs{height:42px;display:flex;gap:2px;padding:5px 8px;border-bottom:1px solid var(--line);overflow-x:auto}.tab{background:transparent;border:0;color:var(--muted);white-space:nowrap}.tab.active{color:var(--text);background:#252b36}.content{flex:1;overflow:auto;padding:18px}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.card{background:var(--panel);border:1px solid var(--line);border-radius:9px;padding:13px}.value{font-size:24px;font-weight:700}.label,.muted{color:var(--muted)}
pre{white-space:pre-wrap;word-break:break-word;background:#0f1116;border:1px solid var(--line);border-radius:8px;padding:14px;font:12px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace}.error{border:1px solid #743844;background:#26171b;color:#ffc2ca;padding:12px;border-radius:8px;margin-bottom:12px}.edge{display:grid;grid-template-columns:minmax(120px,1fr) 36px minmax(120px,1fr) 90px;gap:8px;padding:8px;border-bottom:1px solid var(--line)}.component{border-left:3px solid var(--accent)}.component.effect{border-left-color:var(--bad)}.component.rust{border-left-color:var(--rust)}.component.external{border-left-color:var(--muted)}.component.data{border-left-color:var(--ok)}.symbol{display:grid;grid-template-columns:50px 120px 1fr 1fr;gap:9px;padding:7px;border-bottom:1px solid var(--line)}h2{font-size:16px;margin:5px 0 12px}h3{font-size:14px;margin:18px 0 8px}
.algorithm{margin-bottom:24px}.algorithm-step{border:1px solid var(--line);background:var(--panel);border-radius:10px;margin:9px 0;padding:12px;cursor:pointer}.algorithm-step:hover{border-color:var(--accent)}.step-head{display:flex;align-items:baseline;gap:9px;margin-bottom:9px}.step-name{font-weight:750}.type{font:12px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--ok)}.line{margin-left:auto;color:var(--muted)}.branches{display:grid;gap:6px}.branch{display:grid;grid-template-columns:minmax(120px,1fr) 30px minmax(120px,1fr);gap:8px;padding:8px;background:#11141a;border-radius:7px}.pipeline{display:flex;align-items:stretch;gap:7px;overflow-x:auto;padding:4px 0}.stage{min-width:145px;background:#11141a;border:1px solid var(--line);border-radius:8px;padding:9px;cursor:pointer}.stage.lambda{border-color:#7461a8}.stage.rust{border-color:var(--rust)}.stage.effect{border-color:var(--bad)}.stage.function{border-color:var(--accent)}.stage .kind{text-transform:uppercase;font-size:10px;letter-spacing:.08em;color:var(--muted)}.pipe-arrow{display:flex;align-items:center;color:var(--muted);font-size:18px}.err{color:var(--bad);font-size:11px;margin-top:5px}.expression{font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;background:#11141a;padding:9px;border-radius:7px}.return-step{border-color:var(--ok)}
</style>
</head>
<body>
<header><div class="brand">Glyph Studio</div><div id="path" class="path"></div><div id="status" class="status">starting</div><button id="rebuild">Rebuild</button><button id="save" class="primary">Save</button></header>
<main><section class="editor-pane"><div class="pane-title">Source</div><textarea id="editor" spellcheck="false"></textarea></section><section class="viewer"><nav id="tabs" class="tabs"></nav><div id="content" class="content"></div></section></main>
<script>
const tabs=['Overview','Architecture','State','Logic','Flow','Time','Rust','Host','Manual','AST','Symbols','Artifacts'];let active='Overview',state=null,dirty=false,lastVersion=-1;
const editor=document.getElementById('editor'),content=document.getElementById('content');editor.addEventListener('input',()=>dirty=true);
document.getElementById('save').onclick=async()=>{await post('/api/save',{source:editor.value});dirty=false;await refresh(true)};document.getElementById('rebuild').onclick=async()=>{await post('/api/rebuild',{});await refresh(true)};
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function post(url,body){return fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
async function artifact(name){const r=await fetch('/api/artifact?name='+encodeURIComponent(name));const x=await r.json();return x.content||''}
function goLine(line){const n=Math.max(1,Number(line)||1),text=editor.value,parts=text.split('\n');let start=0;for(let i=1;i<n;i++)start+=parts[i-1].length+1;const end=start+(parts[n-1]||'').length;editor.focus();editor.setSelectionRange(start,end);const lh=parseFloat(getComputedStyle(editor).lineHeight)||20;editor.scrollTop=Math.max(0,(n-3)*lh)}
function makeTabs(){document.getElementById('tabs').innerHTML=tabs.map(t=>`<button class="tab ${t===active?'active':''}" data-t="${t}">${t}</button>`).join('');document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{active=b.dataset.t;makeTabs();render()})}
function diagnostics(){return (state.diagnostics||[]).map(d=>`<div class="error">${esc(d.message)}</div>`).join('')}
function overview(){const ir=state.execution_ir||{},sem=state.semantic||{};return diagnostics()+`<div class="cards"><div class="card"><div class="value">${(sem.functions||[]).length}</div><div class="label">Functions</div></div><div class="card"><div class="value">${(sem.blocks||[]).length}</div><div class="label">Algorithm blocks</div></div><div class="card"><div class="value">${(sem.rust_todos||[]).length}</div><div class="label">Rust TODOs</div></div><div class="card"><div class="value">${(ir.machines||[]).length}</div><div class="label">Machines</div></div><div class="card"><div class="value">${(ir.temporal||[]).length}</div><div class="label">Time constraints</div></div><div class="card"><div class="value">${(sem.symbols||[]).length}</div><div class="label">Symbols</div></div></div><h3>Build</h3><pre>Status: ${esc(state.status)}\nUpdated: ${esc(state.updated_at)}\nDigest: ${esc((state.digest||'').slice(0,16))}\nOutput: ${esc(state.output_dir)}</pre>`}
async function architecture(){let data={systems:[]};try{data=JSON.parse(await artifact('architecture-ir.json'))}catch(_){ }const systems=data.systems||[];if(!systems.length)return '<div class="muted">system declaration is not present.</div>';return systems.map(s=>{const byId=Object.fromEntries((s.components||[]).map(c=>[c.id,c]));const cs=(s.components||[]).map(c=>`<div class="card component ${esc(c.kind)}" onclick="goLine(${c.line})"><b>${esc(c.name)}</b><div class="muted">${esc(c.kind)}${c.binding?' · '+esc(c.binding):''} · L${c.line}</div></div>`).join('');const es=(s.edges||[]).map(e=>`<div class="edge" onclick="goLine(${e.line})"><b>${esc(byId[e.source_id]?.name||e.source_id)}</b><span>→</span><b>${esc(byId[e.target_id]?.name||e.target_id)}</b><span class="muted">L${e.line}</span></div>`).join('');return `<h2>${esc(s.name)}</h2><div class="cards">${cs}</div><h3>Connections</h3>${es}`}).join('')}
function stateView(){const ms=state.execution_ir?.machines||[];if(!ms.length)return '<div class="muted">machine declaration is not present.</div>';return ms.map(m=>{const ts=(m.transitions||[]).map(t=>`<div class="edge" onclick="goLine(${t.source?.line||m.source?.line||1})"><b>${esc(t.source_state)}</b><span>→</span><b>${esc(t.target_state)}</b><span>${esc(t.condition)}</span></div>`).join('');return `<h2>${esc(m.name)}</h2><pre>initial: ${esc(m.initial_state)}\nsuccess: ${esc(m.success_state)}\nfailure: ${esc(m.failure_state)}</pre><h3>Transitions</h3>${ts}`}).join('')}
function renderPipeline(v){const first=`<div class="stage value"><div class="kind">INPUT</div><b>${esc(v.input_text||'value')}</b><div class="muted">${esc(v.input_type||'')}</div></div>`;const stages=(v.stages||[]).map(s=>`<div class="pipe-arrow">→</div><div class="stage ${esc(s.kind)}" onclick="event.stopPropagation();goLine(${s.source?.line||1})"><div class="kind">${esc(s.kind)}</div><b>${esc(s.label)}</b><div class="muted">${esc(s.input_type||'?')} → ${esc(s.output_type||'?')} · L${s.source?.line||0}</div>${s.propagates?'<div class="err">Err exits this function</div>':''}</div>`).join('');return `<div class="pipeline">${first}${stages}</div>`}
function renderValue(v){if(v.kind==='conditional')return `<div class="branches">${(v.branches||[]).map(b=>`<div class="branch" onclick="event.stopPropagation();goLine(${b.source?.line||1})"><b>${esc(b.condition==='_'?'otherwise':b.condition)}</b><span>→</span><span>${esc(b.value)}${(b.binders||[]).length?`<div class="muted">bind ${esc(b.binders.join(', '))}</div>`:''}</span></div>`).join('')}</div>`;if(v.kind==='pipeline')return renderPipeline(v);return `<div class="expression">${esc(v.source_text)}</div>`}
async function logic(){let data={functions:[]};try{data=JSON.parse(await artifact('algorithm-ir.json'))}catch(_){ }const fs=data.functions||[];if(!fs.length)return '<div class="muted">No := algorithm blocks. Lowered compiler helpers are intentionally hidden.</div>';return fs.map(f=>`<section class="algorithm"><h2 onclick="goLine(${f.source?.line||1})">${esc(f.name)} <span class="type">→ ${esc(f.return_type)}</span></h2>${(f.steps||[]).map(s=>`<div class="algorithm-step ${s.kind==='return'?'return-step':''}" onclick="goLine(${s.source?.line||1})"><div class="step-head"><span class="step-name">${s.kind==='return'?'return':esc(s.name)}</span><span class="type">${esc(s.type)}</span><span class="line">L${s.source?.line||0}</span></div>${renderValue(s.value||{})}</div>`).join('')}</section>`).join('')}
function flowView(){const ir=state.execution_ir||{},nodes=ir.nodes||[],edges=ir.edges||[];const ns=nodes.map(n=>`<div class="card component ${esc(n.kind)}" onclick="goLine(${n.source?.line||1})"><b>${esc(n.label)}</b><div class="muted">${esc(n.kind)} · L${n.source?.line||0}</div></div>`).join('');const es=edges.map(e=>`<div class="edge" onclick="goLine(${e.source?.line||1})"><b>${esc(e.source_id)}</b><span>→</span><b>${esc(e.target_id)}</b><span>${esc(e.label||e.kind)}</span></div>`).join('');return `<h2>Lowered execution flow</h2><div class="cards">${ns}</div><h3>Edges</h3>${es||'<div class="muted">No execution edges.</div>'}`}
function timeView(){const xs=state.execution_ir?.temporal||[];return `<h2>Time and safety constraints</h2>${xs.map(x=>`<div class="card" style="margin-bottom:9px" onclick="goLine(${x.source?.line||1})"><b>${esc(x.name)}</b><pre>${esc(x.formula)}</pre><div class="muted">${esc(x.streaming_monitor)}</div></div>`).join('')||'<div class="muted">No temporal constraints.</div>'}`}
async function code(name){content.innerHTML='<div class="muted">loading…</div>';content.innerHTML='<pre>'+esc(await artifact(name))+'</pre>'}
function ast(){return '<pre>'+esc(JSON.stringify(state.semantic||{},null,2))+'</pre>'}
function symbols(){return `<div class="symbol muted"><span>ID</span><span>Kind</span><span>Name</span><span>Type</span></div>${(state.semantic?.symbols||[]).filter(s=>!String(s.name||'').startsWith('__glyph_')).map(s=>`<div class="symbol"><span>${s.id}</span><span>${esc(s.kind)}</span><b>${esc(s.name)}</b><span>${esc(s.type||'')}</span></div>`).join('')}`}
function artifacts(){return `<h2>Generated automatically</h2>${(state.artifact_names||[]).map(n=>`<div class="card" style="margin-bottom:8px"><b>${esc(n)}</b><div class="muted">${esc(state.output_dir+'/'+n)}</div></div>`).join('')}`}
async function render(){if(!state)return;document.getElementById('path').textContent=state.source_path;const st=document.getElementById('status');st.textContent=state.status;st.className='status '+state.status;if(active==='Overview')content.innerHTML=overview();else if(active==='Architecture')content.innerHTML=await architecture();else if(active==='State')content.innerHTML=stateView();else if(active==='Logic')content.innerHTML=await logic();else if(active==='Flow')content.innerHTML=flowView();else if(active==='Time')content.innerHTML=timeView();else if(active==='Rust')await code('generated.rs');else if(active==='Host')await code('host.generated.rs');else if(active==='Manual')await code('manual.rs');else if(active==='AST')content.innerHTML=ast();else if(active==='Symbols')content.innerHTML=symbols();else content.innerHTML=artifacts()}
async function refresh(force=false){const r=await fetch('/api/state',{cache:'no-store'});const next=await r.json();if(force||next.version!==lastVersion){state=next;lastVersion=next.version;if(!dirty)editor.value=state.source||'';await render()}}
makeTabs();refresh(true);setInterval(()=>refresh(false),600);
</script>
</body></html>'''
