// @generated by glyphc. Do not edit by hand.
#![allow(dead_code)]

#[derive(Debug, Clone, PartialEq)]
pub struct Input {
    pub voltage: f32,
    pub temperature: f32,
    pub requested: u16,
    pub authorized: bool,
    pub emergency: bool,
    pub fault: bool,
    pub send: bool,
    pub ack: bool,
    pub heartbeat: bool,
    pub closed: bool,
    pub stable: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Mode {
    Idle,
    Running,
    Stopping,
    Faulted,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Command {
    Stop,
    Run(u16),
    EmergencyStop,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Error {
    BadSensor,
    Actuator,
}

#[derive(Debug, Clone, PartialEq)]
pub struct System {
    pub mode: Mode,
    pub sequence: u16,
    pub last_speed: u16,
    pub command: Command,
    pub closed: bool,
    pub stable: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Receipt {
    pub command: Command,
    pub sequence: u16,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Cycle {
    pub system: System,
    pub receipt: Receipt,
}

pub fn validate(input: Input) -> Result<Input, Error> {
    if !input.voltage.is_finite() || !input.temperature.is_finite() || input.voltage < 0.0 {
        Err(Error::BadSensor)
    }
    else {
        Ok(input)
    }
}

pub fn decide(input: Input) -> Command {
    if input.emergency {
        Command::EmergencyStop
    }
    else if input.voltage < 10.0 || input.temperature > 80.0 || !input.authorized || input.fault || input.requested == 0 {
        Command::Stop
    }
    else {
        Command::Run(std::cmp::min(input.requested, 1000))
    }
}

pub fn transition(system: System, command: Command) -> System {
    if let Command::Run(__glyph_match_48_0) = (command).clone() {
        if __glyph_match_48_0 == system.last_speed {
            return System { mode: Mode::Running, sequence: system.sequence + 1, last_speed: system.last_speed, command: command, closed: false, stable: true };
        }
    }
    if let Command::Run(__glyph_match_48_0) = (command).clone() {
        let speed = __glyph_match_48_0;
        return System { mode: Mode::Running, sequence: system.sequence + 1, last_speed: speed, command: Command::Run(speed), closed: false, stable: true };
    }
    if let Command::EmergencyStop = (command).clone() {
        return System { mode: Mode::Faulted, sequence: system.sequence + 1, last_speed: system.last_speed, command: Command::EmergencyStop, closed: true, stable: false };
    }
    if let Command::Stop = (command).clone() {
        return System { mode: Mode::Stopping, sequence: system.sequence + 1, last_speed: system.last_speed, command: Command::Stop, closed: true, stable: false };
    }
    system
}

pub fn step(state: System, input: Input) -> Result<System, Error> {
    Ok(transition(state, decide(validate(input)?)))
}

// effect boundary: write_actuator(system: System) -> Result<Cycle, Error>

// effect boundary: report_violation(code: u16) -> Result<bool, Error>

pub fn cycle(system: System, input: Input) -> Result<Cycle, Error> {
    crate::host::write_actuator(step(system, input)?)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TemporalVerdict {
    Satisfied,
    Violated,
    Pending,
}

fn temporal_not(value: TemporalVerdict) -> TemporalVerdict {
    match value {
        TemporalVerdict::Satisfied => TemporalVerdict::Violated,
        TemporalVerdict::Violated => TemporalVerdict::Satisfied,
        TemporalVerdict::Pending => TemporalVerdict::Pending,
    }
}

fn temporal_and(left: TemporalVerdict, right: TemporalVerdict) -> TemporalVerdict {
    match (left, right) {
        (TemporalVerdict::Violated, _) | (_, TemporalVerdict::Violated) => TemporalVerdict::Violated,
        (TemporalVerdict::Satisfied, TemporalVerdict::Satisfied) => TemporalVerdict::Satisfied,
        _ => TemporalVerdict::Pending,
    }
}

fn temporal_or(left: TemporalVerdict, right: TemporalVerdict) -> TemporalVerdict {
    match (left, right) {
        (TemporalVerdict::Satisfied, _) | (_, TemporalVerdict::Satisfied) => TemporalVerdict::Satisfied,
        (TemporalVerdict::Violated, TemporalVerdict::Violated) => TemporalVerdict::Violated,
        _ => TemporalVerdict::Pending,
    }
}

#[derive(Debug, Clone)]
struct AckDeadlineObservation {
    at_ms: u64,
    voltage: f32,
    temperature: f32,
    requested: u16,
    authorized: bool,
    emergency: bool,
    fault: bool,
    send: bool,
    ack: bool,
    heartbeat: bool,
    closed: bool,
    stable: bool,
}

#[derive(Debug, Default)]
pub struct AckDeadlineMonitor {
    trace: Vec<AckDeadlineObservation>,
}

impl AckDeadlineMonitor {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn step(&mut self, at_ms: u64, voltage: f32, temperature: f32, requested: u16, authorized: bool, emergency: bool, fault: bool, send: bool, ack: bool, heartbeat: bool, closed: bool, stable: bool) -> TemporalVerdict {
        if let Some(last) = self.trace.last() {
            assert!(at_ms >= last.at_ms, "temporal observation time must be monotonic");
        }
        self.trace.push(AckDeadlineObservation { at_ms, voltage, temperature, requested, authorized, emergency, fault, send, ack, heartbeat, closed, stable });
        self.eval_4(0, false)
    }

    pub fn verdict(&self) -> TemporalVerdict {
        if self.trace.is_empty() {
            TemporalVerdict::Pending
        } else {
            self.eval_4(0, false)
        }
    }

    pub fn finish(&self) -> TemporalVerdict {
        if self.trace.is_empty() {
            TemporalVerdict::Pending
        } else {
            self.eval_4(0, true)
        }
    }

    pub fn reset(&mut self) {
        self.trace.clear();
    }

    fn eval_0(&self, i: usize, closed: bool) -> TemporalVerdict {
        if i >= self.trace.len() {
            return TemporalVerdict::Pending;
        }
        if self.trace[i].send {
            TemporalVerdict::Satisfied
        } else {
            TemporalVerdict::Violated
        }
    }

    fn eval_1(&self, i: usize, closed: bool) -> TemporalVerdict {
        if i >= self.trace.len() {
            return TemporalVerdict::Pending;
        }
        if self.trace[i].ack {
            TemporalVerdict::Satisfied
        } else {
            TemporalVerdict::Violated
        }
    }

    fn eval_2(&self, i: usize, closed: bool) -> TemporalVerdict {
        if i >= self.trace.len() {
            return TemporalVerdict::Pending;
        }
        let deadline = self.trace[i].at_ms.saturating_add(500);
        for j in i..self.trace.len() {
            if self.trace[j].at_ms > deadline {
                break;
            }
            if self.eval_1(j, closed) == TemporalVerdict::Satisfied {
                return TemporalVerdict::Satisfied;
            }
        }
        if closed || self.trace.last().is_some_and(|last| last.at_ms > deadline) {
            TemporalVerdict::Violated
        } else {
            TemporalVerdict::Pending
        }
    }

    fn eval_3(&self, i: usize, closed: bool) -> TemporalVerdict {
        temporal_or(temporal_not(self.eval_0(i, closed)), self.eval_2(i, closed))
    }

    fn eval_4(&self, i: usize, closed: bool) -> TemporalVerdict {
        let mut all_satisfied = true;
        for j in i..self.trace.len() {
            match self.eval_3(j, closed) {
                TemporalVerdict::Violated => return TemporalVerdict::Violated,
                TemporalVerdict::Pending => all_satisfied = false,
                TemporalVerdict::Satisfied => {}
            }
        }
        if closed && all_satisfied {
            TemporalVerdict::Satisfied
        } else {
            TemporalVerdict::Pending
        }
    }

}

#[derive(Debug, Clone)]
struct HeartbeatLiveObservation {
    at_ms: u64,
    voltage: f32,
    temperature: f32,
    requested: u16,
    authorized: bool,
    emergency: bool,
    fault: bool,
    send: bool,
    ack: bool,
    heartbeat: bool,
    closed: bool,
    stable: bool,
}

#[derive(Debug, Default)]
pub struct HeartbeatLiveMonitor {
    trace: Vec<HeartbeatLiveObservation>,
}

impl HeartbeatLiveMonitor {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn step(&mut self, at_ms: u64, voltage: f32, temperature: f32, requested: u16, authorized: bool, emergency: bool, fault: bool, send: bool, ack: bool, heartbeat: bool, closed: bool, stable: bool) -> TemporalVerdict {
        if let Some(last) = self.trace.last() {
            assert!(at_ms >= last.at_ms, "temporal observation time must be monotonic");
        }
        self.trace.push(HeartbeatLiveObservation { at_ms, voltage, temperature, requested, authorized, emergency, fault, send, ack, heartbeat, closed, stable });
        self.eval_2(0, false)
    }

    pub fn verdict(&self) -> TemporalVerdict {
        if self.trace.is_empty() {
            TemporalVerdict::Pending
        } else {
            self.eval_2(0, false)
        }
    }

    pub fn finish(&self) -> TemporalVerdict {
        if self.trace.is_empty() {
            TemporalVerdict::Pending
        } else {
            self.eval_2(0, true)
        }
    }

    pub fn reset(&mut self) {
        self.trace.clear();
    }

    fn eval_0(&self, i: usize, closed: bool) -> TemporalVerdict {
        if i >= self.trace.len() {
            return TemporalVerdict::Pending;
        }
        if self.trace[i].heartbeat {
            TemporalVerdict::Satisfied
        } else {
            TemporalVerdict::Violated
        }
    }

    fn eval_1(&self, i: usize, closed: bool) -> TemporalVerdict {
        if i >= self.trace.len() {
            return TemporalVerdict::Pending;
        }
        let deadline = self.trace[i].at_ms.saturating_add(1000);
        for j in i..self.trace.len() {
            if self.trace[j].at_ms > deadline {
                break;
            }
            if self.eval_0(j, closed) == TemporalVerdict::Satisfied {
                return TemporalVerdict::Satisfied;
            }
        }
        if closed || self.trace.last().is_some_and(|last| last.at_ms > deadline) {
            TemporalVerdict::Violated
        } else {
            TemporalVerdict::Pending
        }
    }

    fn eval_2(&self, i: usize, closed: bool) -> TemporalVerdict {
        let mut all_satisfied = true;
        for j in i..self.trace.len() {
            match self.eval_1(j, closed) {
                TemporalVerdict::Violated => return TemporalVerdict::Violated,
                TemporalVerdict::Pending => all_satisfied = false,
                TemporalVerdict::Satisfied => {}
            }
        }
        if closed && all_satisfied {
            TemporalVerdict::Satisfied
        } else {
            TemporalVerdict::Pending
        }
    }

}

#[derive(Debug, Clone)]
struct AuthorizationSafeObservation {
    at_ms: u64,
    voltage: f32,
    temperature: f32,
    requested: u16,
    authorized: bool,
    emergency: bool,
    fault: bool,
    send: bool,
    ack: bool,
    heartbeat: bool,
    closed: bool,
    stable: bool,
}

#[derive(Debug, Default)]
pub struct AuthorizationSafeMonitor {
    trace: Vec<AuthorizationSafeObservation>,
}

impl AuthorizationSafeMonitor {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn step(&mut self, at_ms: u64, voltage: f32, temperature: f32, requested: u16, authorized: bool, emergency: bool, fault: bool, send: bool, ack: bool, heartbeat: bool, closed: bool, stable: bool) -> TemporalVerdict {
        if let Some(last) = self.trace.last() {
            assert!(at_ms >= last.at_ms, "temporal observation time must be monotonic");
        }
        self.trace.push(AuthorizationSafeObservation { at_ms, voltage, temperature, requested, authorized, emergency, fault, send, ack, heartbeat, closed, stable });
        self.eval_4(0, false)
    }

    pub fn verdict(&self) -> TemporalVerdict {
        if self.trace.is_empty() {
            TemporalVerdict::Pending
        } else {
            self.eval_4(0, false)
        }
    }

    pub fn finish(&self) -> TemporalVerdict {
        if self.trace.is_empty() {
            TemporalVerdict::Pending
        } else {
            self.eval_4(0, true)
        }
    }

    pub fn reset(&mut self) {
        self.trace.clear();
    }

    fn eval_0(&self, i: usize, closed: bool) -> TemporalVerdict {
        if i >= self.trace.len() {
            return TemporalVerdict::Pending;
        }
        if self.trace[i].authorized {
            TemporalVerdict::Satisfied
        } else {
            TemporalVerdict::Violated
        }
    }

    fn eval_1(&self, i: usize, closed: bool) -> TemporalVerdict {
        temporal_not(self.eval_0(i, closed))
    }

    fn eval_2(&self, i: usize, closed: bool) -> TemporalVerdict {
        if i >= self.trace.len() {
            return TemporalVerdict::Pending;
        }
        if self.trace[i].closed {
            TemporalVerdict::Satisfied
        } else {
            TemporalVerdict::Violated
        }
    }

    fn eval_3(&self, i: usize, closed: bool) -> TemporalVerdict {
        temporal_or(temporal_not(self.eval_1(i, closed)), self.eval_2(i, closed))
    }

    fn eval_4(&self, i: usize, closed: bool) -> TemporalVerdict {
        let mut all_satisfied = true;
        for j in i..self.trace.len() {
            match self.eval_3(j, closed) {
                TemporalVerdict::Violated => return TemporalVerdict::Violated,
                TemporalVerdict::Pending => all_satisfied = false,
                TemporalVerdict::Satisfied => {}
            }
        }
        if closed && all_satisfied {
            TemporalVerdict::Satisfied
        } else {
            TemporalVerdict::Pending
        }
    }

}

#[derive(Debug, Clone)]
struct EmergencySafeObservation {
    at_ms: u64,
    voltage: f32,
    temperature: f32,
    requested: u16,
    authorized: bool,
    emergency: bool,
    fault: bool,
    send: bool,
    ack: bool,
    heartbeat: bool,
    closed: bool,
    stable: bool,
}

#[derive(Debug, Default)]
pub struct EmergencySafeMonitor {
    trace: Vec<EmergencySafeObservation>,
}

impl EmergencySafeMonitor {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn step(&mut self, at_ms: u64, voltage: f32, temperature: f32, requested: u16, authorized: bool, emergency: bool, fault: bool, send: bool, ack: bool, heartbeat: bool, closed: bool, stable: bool) -> TemporalVerdict {
        if let Some(last) = self.trace.last() {
            assert!(at_ms >= last.at_ms, "temporal observation time must be monotonic");
        }
        self.trace.push(EmergencySafeObservation { at_ms, voltage, temperature, requested, authorized, emergency, fault, send, ack, heartbeat, closed, stable });
        self.eval_3(0, false)
    }

    pub fn verdict(&self) -> TemporalVerdict {
        if self.trace.is_empty() {
            TemporalVerdict::Pending
        } else {
            self.eval_3(0, false)
        }
    }

    pub fn finish(&self) -> TemporalVerdict {
        if self.trace.is_empty() {
            TemporalVerdict::Pending
        } else {
            self.eval_3(0, true)
        }
    }

    pub fn reset(&mut self) {
        self.trace.clear();
    }

    fn eval_0(&self, i: usize, closed: bool) -> TemporalVerdict {
        if i >= self.trace.len() {
            return TemporalVerdict::Pending;
        }
        if self.trace[i].emergency {
            TemporalVerdict::Satisfied
        } else {
            TemporalVerdict::Violated
        }
    }

    fn eval_1(&self, i: usize, closed: bool) -> TemporalVerdict {
        if i >= self.trace.len() {
            return TemporalVerdict::Pending;
        }
        if self.trace[i].closed {
            TemporalVerdict::Satisfied
        } else {
            TemporalVerdict::Violated
        }
    }

    fn eval_2(&self, i: usize, closed: bool) -> TemporalVerdict {
        temporal_or(temporal_not(self.eval_0(i, closed)), self.eval_1(i, closed))
    }

    fn eval_3(&self, i: usize, closed: bool) -> TemporalVerdict {
        let mut all_satisfied = true;
        for j in i..self.trace.len() {
            match self.eval_2(j, closed) {
                TemporalVerdict::Violated => return TemporalVerdict::Violated,
                TemporalVerdict::Pending => all_satisfied = false,
                TemporalVerdict::Satisfied => {}
            }
        }
        if closed && all_satisfied {
            TemporalVerdict::Satisfied
        } else {
            TemporalVerdict::Pending
        }
    }

}

#[derive(Debug, Clone)]
struct FaultSafeObservation {
    at_ms: u64,
    voltage: f32,
    temperature: f32,
    requested: u16,
    authorized: bool,
    emergency: bool,
    fault: bool,
    send: bool,
    ack: bool,
    heartbeat: bool,
    closed: bool,
    stable: bool,
}

#[derive(Debug, Default)]
pub struct FaultSafeMonitor {
    trace: Vec<FaultSafeObservation>,
}

impl FaultSafeMonitor {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn step(&mut self, at_ms: u64, voltage: f32, temperature: f32, requested: u16, authorized: bool, emergency: bool, fault: bool, send: bool, ack: bool, heartbeat: bool, closed: bool, stable: bool) -> TemporalVerdict {
        if let Some(last) = self.trace.last() {
            assert!(at_ms >= last.at_ms, "temporal observation time must be monotonic");
        }
        self.trace.push(FaultSafeObservation { at_ms, voltage, temperature, requested, authorized, emergency, fault, send, ack, heartbeat, closed, stable });
        self.eval_3(0, false)
    }

    pub fn verdict(&self) -> TemporalVerdict {
        if self.trace.is_empty() {
            TemporalVerdict::Pending
        } else {
            self.eval_3(0, false)
        }
    }

    pub fn finish(&self) -> TemporalVerdict {
        if self.trace.is_empty() {
            TemporalVerdict::Pending
        } else {
            self.eval_3(0, true)
        }
    }

    pub fn reset(&mut self) {
        self.trace.clear();
    }

    fn eval_0(&self, i: usize, closed: bool) -> TemporalVerdict {
        if i >= self.trace.len() {
            return TemporalVerdict::Pending;
        }
        if self.trace[i].fault {
            TemporalVerdict::Satisfied
        } else {
            TemporalVerdict::Violated
        }
    }

    fn eval_1(&self, i: usize, closed: bool) -> TemporalVerdict {
        if i >= self.trace.len() {
            return TemporalVerdict::Pending;
        }
        if self.trace[i].closed {
            TemporalVerdict::Satisfied
        } else {
            TemporalVerdict::Violated
        }
    }

    fn eval_2(&self, i: usize, closed: bool) -> TemporalVerdict {
        temporal_or(temporal_not(self.eval_0(i, closed)), self.eval_1(i, closed))
    }

    fn eval_3(&self, i: usize, closed: bool) -> TemporalVerdict {
        let mut all_satisfied = true;
        for j in i..self.trace.len() {
            match self.eval_2(j, closed) {
                TemporalVerdict::Violated => return TemporalVerdict::Violated,
                TemporalVerdict::Pending => all_satisfied = false,
                TemporalVerdict::Satisfied => {}
            }
        }
        if closed && all_satisfied {
            TemporalVerdict::Satisfied
        } else {
            TemporalVerdict::Pending
        }
    }

}

#[derive(Debug, Clone)]
struct ConvergenceObservation {
    at_ms: u64,
    voltage: f32,
    temperature: f32,
    requested: u16,
    authorized: bool,
    emergency: bool,
    fault: bool,
    send: bool,
    ack: bool,
    heartbeat: bool,
    closed: bool,
    stable: bool,
}

#[derive(Debug, Default)]
pub struct ConvergenceMonitor {
    trace: Vec<ConvergenceObservation>,
}

impl ConvergenceMonitor {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn step(&mut self, at_ms: u64, voltage: f32, temperature: f32, requested: u16, authorized: bool, emergency: bool, fault: bool, send: bool, ack: bool, heartbeat: bool, closed: bool, stable: bool) -> TemporalVerdict {
        if let Some(last) = self.trace.last() {
            assert!(at_ms >= last.at_ms, "temporal observation time must be monotonic");
        }
        self.trace.push(ConvergenceObservation { at_ms, voltage, temperature, requested, authorized, emergency, fault, send, ack, heartbeat, closed, stable });
        self.eval_2(0, false)
    }

    pub fn verdict(&self) -> TemporalVerdict {
        if self.trace.is_empty() {
            TemporalVerdict::Pending
        } else {
            self.eval_2(0, false)
        }
    }

    pub fn finish(&self) -> TemporalVerdict {
        if self.trace.is_empty() {
            TemporalVerdict::Pending
        } else {
            self.eval_2(0, true)
        }
    }

    pub fn reset(&mut self) {
        self.trace.clear();
    }

    fn eval_0(&self, i: usize, closed: bool) -> TemporalVerdict {
        if i >= self.trace.len() {
            return TemporalVerdict::Pending;
        }
        if self.trace[i].stable {
            TemporalVerdict::Satisfied
        } else {
            TemporalVerdict::Violated
        }
    }

    fn eval_1(&self, i: usize, closed: bool) -> TemporalVerdict {
        let mut all_satisfied = true;
        for j in i..self.trace.len() {
            match self.eval_0(j, closed) {
                TemporalVerdict::Violated => return TemporalVerdict::Violated,
                TemporalVerdict::Pending => all_satisfied = false,
                TemporalVerdict::Satisfied => {}
            }
        }
        if closed && all_satisfied {
            TemporalVerdict::Satisfied
        } else {
            TemporalVerdict::Pending
        }
    }

    fn eval_2(&self, i: usize, closed: bool) -> TemporalVerdict {
        for j in i..self.trace.len() {
            if self.eval_1(j, closed) == TemporalVerdict::Satisfied {
                return TemporalVerdict::Satisfied;
            }
        }
        if closed {
            TemporalVerdict::Violated
        } else {
            TemporalVerdict::Pending
        }
    }

}

#[derive(Debug, Default)]
pub struct AckDeadlineStreamingMonitor {
    seen: bool,
    last_at_ms: Option<u64>,
    pending_deadline_ms: Option<u64>,
    violated: bool,
}

impl AckDeadlineStreamingMonitor {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn step(&mut self, at_ms: u64, voltage: f32, temperature: f32, requested: u16, authorized: bool, emergency: bool, fault: bool, send: bool, ack: bool, heartbeat: bool, closed: bool, stable: bool) -> TemporalVerdict {
        if let Some(last) = self.last_at_ms {
            assert!(at_ms >= last, "temporal observation time must be monotonic");
        }
        self.last_at_ms = Some(at_ms);
        self.seen = true;
        if let Some(deadline) = self.pending_deadline_ms {
            if at_ms > deadline {
                self.violated = true;
            }
        }
        if !self.violated {
            if ack {
                self.pending_deadline_ms = None;
            } else if send && self.pending_deadline_ms.is_none() {
                self.pending_deadline_ms = Some(at_ms.saturating_add(500));
            }
        }
        self.verdict()
    }

    pub fn verdict(&self) -> TemporalVerdict {
        if self.violated {
            TemporalVerdict::Violated
        } else {
            TemporalVerdict::Pending
        }
    }

    pub fn finish(&self) -> TemporalVerdict {
        if !self.seen {
            TemporalVerdict::Pending
        } else if self.violated || self.pending_deadline_ms.is_some() {
            TemporalVerdict::Violated
        } else {
            TemporalVerdict::Satisfied
        }
    }

    pub fn reset(&mut self) {
        *self = Self::default();
    }
}

#[derive(Debug, Default)]
pub struct HeartbeatLiveStreamingMonitor {
    seen: bool,
    last_at_ms: Option<u64>,
    pending_deadline_ms: Option<u64>,
    violated: bool,
}

impl HeartbeatLiveStreamingMonitor {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn step(&mut self, at_ms: u64, voltage: f32, temperature: f32, requested: u16, authorized: bool, emergency: bool, fault: bool, send: bool, ack: bool, heartbeat: bool, closed: bool, stable: bool) -> TemporalVerdict {
        if let Some(last) = self.last_at_ms {
            assert!(at_ms >= last, "temporal observation time must be monotonic");
        }
        self.last_at_ms = Some(at_ms);
        self.seen = true;
        if let Some(deadline) = self.pending_deadline_ms {
            if at_ms > deadline {
                self.violated = true;
            }
        }
        if !self.violated {
            if heartbeat {
                self.pending_deadline_ms = None;
            } else if self.pending_deadline_ms.is_none() {
                self.pending_deadline_ms = Some(at_ms.saturating_add(1000));
            }
        }
        self.verdict()
    }

    pub fn verdict(&self) -> TemporalVerdict {
        if self.violated {
            TemporalVerdict::Violated
        } else {
            TemporalVerdict::Pending
        }
    }

    pub fn finish(&self) -> TemporalVerdict {
        if !self.seen {
            TemporalVerdict::Pending
        } else if self.violated || self.pending_deadline_ms.is_some() {
            TemporalVerdict::Violated
        } else {
            TemporalVerdict::Satisfied
        }
    }

    pub fn reset(&mut self) {
        *self = Self::default();
    }
}

#[derive(Debug, Default)]
pub struct ConvergenceStreamingMonitor {
    seen: bool,
    last_at_ms: Option<u64>,
    last_value: bool,
}

impl ConvergenceStreamingMonitor {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn step(&mut self, at_ms: u64, voltage: f32, temperature: f32, requested: u16, authorized: bool, emergency: bool, fault: bool, send: bool, ack: bool, heartbeat: bool, closed: bool, stable: bool) -> TemporalVerdict {
        if let Some(last) = self.last_at_ms {
            assert!(at_ms >= last, "temporal observation time must be monotonic");
        }
        self.last_at_ms = Some(at_ms);
        self.seen = true;
        self.last_value = stable;
        TemporalVerdict::Pending
    }

    pub fn verdict(&self) -> TemporalVerdict {
        TemporalVerdict::Pending
    }

    pub fn finish(&self) -> TemporalVerdict {
        if !self.seen {
            TemporalVerdict::Pending
        } else if self.last_value {
            TemporalVerdict::Satisfied
        } else {
            TemporalVerdict::Violated
        }
    }

    pub fn reset(&mut self) {
        *self = Self::default();
    }
}

#[derive(Debug, Default)]
pub struct AuthorizationSafeStreamingMonitor {
    seen: bool,
    last_at_ms: Option<u64>,
    violated: bool,
}

impl AuthorizationSafeStreamingMonitor {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn step(&mut self, at_ms: u64, voltage: f32, temperature: f32, requested: u16, authorized: bool, emergency: bool, fault: bool, send: bool, ack: bool, heartbeat: bool, closed: bool, stable: bool) -> TemporalVerdict {
        if let Some(last) = self.last_at_ms {
            assert!(at_ms >= last, "temporal observation time must be monotonic");
        }
        self.last_at_ms = Some(at_ms);
        self.seen = true;
        if !(!(!(authorized)) || (closed)) {
            self.violated = true;
        }
        self.verdict()
    }

    pub fn verdict(&self) -> TemporalVerdict {
        if self.violated {
            TemporalVerdict::Violated
        } else {
            TemporalVerdict::Pending
        }
    }

    pub fn finish(&self) -> TemporalVerdict {
        if !self.seen {
            TemporalVerdict::Pending
        } else if self.violated {
            TemporalVerdict::Violated
        } else {
            TemporalVerdict::Satisfied
        }
    }

    pub fn reset(&mut self) {
        *self = Self::default();
    }
}

#[derive(Debug, Default)]
pub struct EmergencySafeStreamingMonitor {
    seen: bool,
    last_at_ms: Option<u64>,
    violated: bool,
}

impl EmergencySafeStreamingMonitor {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn step(&mut self, at_ms: u64, voltage: f32, temperature: f32, requested: u16, authorized: bool, emergency: bool, fault: bool, send: bool, ack: bool, heartbeat: bool, closed: bool, stable: bool) -> TemporalVerdict {
        if let Some(last) = self.last_at_ms {
            assert!(at_ms >= last, "temporal observation time must be monotonic");
        }
        self.last_at_ms = Some(at_ms);
        self.seen = true;
        if !(!(emergency) || (closed)) {
            self.violated = true;
        }
        self.verdict()
    }

    pub fn verdict(&self) -> TemporalVerdict {
        if self.violated {
            TemporalVerdict::Violated
        } else {
            TemporalVerdict::Pending
        }
    }

    pub fn finish(&self) -> TemporalVerdict {
        if !self.seen {
            TemporalVerdict::Pending
        } else if self.violated {
            TemporalVerdict::Violated
        } else {
            TemporalVerdict::Satisfied
        }
    }

    pub fn reset(&mut self) {
        *self = Self::default();
    }
}

#[derive(Debug, Default)]
pub struct FaultSafeStreamingMonitor {
    seen: bool,
    last_at_ms: Option<u64>,
    violated: bool,
}

impl FaultSafeStreamingMonitor {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn step(&mut self, at_ms: u64, voltage: f32, temperature: f32, requested: u16, authorized: bool, emergency: bool, fault: bool, send: bool, ack: bool, heartbeat: bool, closed: bool, stable: bool) -> TemporalVerdict {
        if let Some(last) = self.last_at_ms {
            assert!(at_ms >= last, "temporal observation time must be monotonic");
        }
        self.last_at_ms = Some(at_ms);
        self.seen = true;
        if !(!(fault) || (closed)) {
            self.violated = true;
        }
        self.verdict()
    }

    pub fn verdict(&self) -> TemporalVerdict {
        if self.violated {
            TemporalVerdict::Violated
        } else {
            TemporalVerdict::Pending
        }
    }

    pub fn finish(&self) -> TemporalVerdict {
        if !self.seen {
            TemporalVerdict::Pending
        } else if self.violated {
            TemporalVerdict::Violated
        } else {
            TemporalVerdict::Satisfied
        }
    }

    pub fn reset(&mut self) {
        *self = Self::default();
    }
}
