// @generated by glyphc. Do not edit by hand.
use crate::generated::*;

#[allow(unused_variables)]
pub fn write_actuator(system: System) -> Result<Cycle, Error> {
    panic!("Glyph effect boundary `write_actuator` is not connected")
}

#[allow(unused_variables)]
pub fn report_violation(code: u16) -> Result<bool, Error> {
    panic!("Glyph effect boundary `report_violation` is not connected")
}
