// @generated by glyphc. Do not edit by hand.
#![allow(dead_code)]

#[derive(Debug, Clone, PartialEq)]
pub struct S {
    pub v: f32,
    pub t: f32,
    pub r: u16,
}

#[derive(Debug, Clone, PartialEq)]
pub enum C {
    Stop,
    Run(u16),
}

#[derive(Debug, Clone, PartialEq)]
pub enum E {
    BadSensor,
    Actuator,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Receipt {
    pub c: C,
}

pub fn decode(v: f32, t: f32, r: u16) -> Result<S, E> {
    if !v.is_finite() || !t.is_finite() || v < 0.0 {
        Err(E::BadSensor)
    }
    else {
        Ok(S { v: v, t: t, r: r })
    }
}

pub fn cmd(s: S) -> C {
    if s.v < 10.0 || s.t > 80.0 || s.r == 0 {
        C::Stop
    }
    else {
        C::Run(std::cmp::min(s.r, 1000))
    }
}

// effect boundary: exec(c: C) -> Result<Receipt, E>

pub fn run(v: f32, t: f32, r: u16) -> Result<Receipt, E> {
    crate::host::exec(cmd(decode(v, t, r)?))
}
